### ISSUE TITLE
Audio not working after navigation app opens

### ISSUE THREAD

**Issue by wjvdb** [PixelExperience/android-issues#1067]
## Build date

PixelExperience_Plus_raphael-11.0-20211123-2039-OFFICIAL

## Expected Behavior

Music/video should be able to play regardless if it's YouTube Spotify yt music Instagram etc

## Current Behavior

After phone boots it works for a moment but when the phone has been running for a while and a navigation app has been used to navigate (Waze, maps etc.)

(Android 12 version had it immediately without any navigation but that's still in beta)

## Steps to Reproduce

1. Boot phone
2. Play media
3. Start navigation
4. Start a route 
5. Fiddle around with media till it stutters every 2 seconds for half a second

/device Raphael
/version eleven_plus

**Comment by Jorg3Lucas** [comment]
tested, it doesn't happen here so I can fix it, if possible send it in the log here or in the telegram reproducing this problem
