### ISSUE TITLE
Wake up screen in notifications using Ambient Display (AOD)

### ISSUE THREAD

**Issue by indc9** [PixelExperience/android-issues#109]
## Build date

```
PixelExperience_Plus_cepheus-11.0-20210514-0318-OFFICIAL
```

## Expected Behavior

```
When using Ambient Display mode (AOD), the screen should not automatically wake up when notifications are received.
When searching for the option in Settings to deactivate this option ('Wake screen for notifications'), it is already marked as activated, but when I deativate it does not work.
```

## Current Behavior

```
When using Ambient Display mode (AOD), the screen should not automatically wake up when notifications are received (screenshot below)
![1](https://user-images.githubusercontent.com/12446585/120006317-153c1680-bfd9-11eb-996c-77316216e19b.jpg)
When looking for the option in Settings to deactivate this option ('Wake screen for notifications'), it is already marked as activated (screenshot below),
![2](https://user-images.githubusercontent.com/12446585/120006320-15d4ad00-bfd9-11eb-8d4b-bffc47c12477.jpg)
but when I click on it, the 'Lock Screen' settings screen appears and that option does not appear.(screenshot below)
![3](https://user-images.githubusercontent.com/12446585/120006324-15d4ad00-bfd9-11eb-862e-3a7b500633cd.jpg)
If the option 'Activate screen for notifications' is deactivated directly from the search panel (screenshot below),
![2](https://user-images.githubusercontent.com/12446585/120006320-15d4ad00-bfd9-11eb-8d4b-bffc47c12477.jpg)
no more notifications appear automatically when the screen is locked, but the fact is that this option also deactivates the mode 'Ambient display'!(screenshot below)
![4](https://user-images.githubusercontent.com/12446585/120006326-166d4380-bfd9-11eb-99bb-0889afdf4d5a.jpg)
```

## Possible Solution

```
It seems that both options are not working correctly together at the same time
```

## Steps to Reproduce

```
1. Activate Ambient Display mode.
2. Open Settings app.
3. At the search bar, type 'Wake screen for notifications'.
4. If Ambient Display mode is already activated, this option will appear activated too.
5. Deactivate 'Wake screen for notifications'.
6. Go back to step 1 screen and you can check that the Ambient Display mode has been turned off by itself.
```

/device cepheus
/version eleven_plus

**Comment by EcrosoftXiao** [comment]
> ## Build date
> ```
> PixelExperience_Plus_cepheus-11.0-20210514-0318-OFFICIAL
> ```
> 
> ## Expected Behavior
> ```
> When using Ambient Display mode (AOD), the screen should not automatically wake up when notifications are received.
> When searching for the option in Settings to deactivate this option ('Wake screen for notifications'), it is already marked as activated, but when I deativate it does not work.
> ```
> 
> ## Current Behavior
> ```
> When using Ambient Display mode (AOD), the screen should not automatically wake up when notifications are received (screenshot below)
> ![1](https://user-images.githubusercontent.com/12446585/120006317-153c1680-bfd9-11eb-996c-77316216e19b.jpg)
> When looking for the option in Settings to deactivate this option ('Wake screen for notifications'), it is already marked as activated (screenshot below),
> ![2](https://user-images.githubusercontent.com/12446585/120006320-15d4ad00-bfd9-11eb-8d4b-bffc47c12477.jpg)
> but when I click on it, the 'Lock Screen' settings screen appears and that option does not appear.(screenshot below)
> ![3](https://user-images.githubusercontent.com/12446585/120006324-15d4ad00-bfd9-11eb-862e-3a7b500633cd.jpg)
> If the option 'Activate screen for notifications' is deactivated directly from the search panel (screenshot below),
> ![2](https://user-images.githubusercontent.com/12446585/120006320-15d4ad00-bfd9-11eb-8d4b-bffc47c12477.jpg)
> no more notifications appear automatically when the screen is locked, but the fact is that this option also deactivates the mode 'Ambient display'!(screenshot below)
> ![4](https://user-images.githubusercontent.com/12446585/120006326-166d4380-bfd9-11eb-99bb-0889afdf4d5a.jpg)
> ```
> 
> ## Possible Solution
> ```
> It seems that both options are not working correctly together at the same time
> ```
> 
> ## Steps to Reproduce
> ```
> 1. Activate Ambient Display mode.
> 2. Open Settings app.
> 3. At the search bar, type 'Wake screen for notifications'.
> 4. If Ambient Display mode is already activated, this option will appear activated too.
> 5. Deactivate 'Wake screen for notifications'.
> 6. Go back to step 1 screen and you can check that the Ambient Display mode has been turned off by itself.
> ```
> 
> /device cepheus
> /version eleven_plus

That's normal. We are using custom doze package, the normal 'Ambient Display' options means 'Wake screen for notifications'.

**Comment by indc9** [comment]
So sad to hear that, it would be a nice feature :(
Thanks anyway!
