### ISSUE TITLE
OnePlus Nord: Google Recorder not working properly

### ISSUE THREAD

**Issue by ankit98singh** [PixelExperience/android-issues#1108]
## Build date

PixelExperience_Plus_avicii-11.0-20211011-1108-OFFICIAL.zip

## Expected Behavior

Pressing "Record" should start recording and Live Transcript feature should work as intended

## Current Behavior

Pressing "Record" does not start recording audio and the Live transcription feature is also not working; Also this messes up the bluetooth earphones audio connection, e.g. in my case, I'm using Realme Wireless Buds 2

## Possible Solution

I cant suggest anything, but merely ask you to look into the issue from your side. This may also be a bug with the Recorder app and may need to be fixed from the Google team as well

## Steps to Reproduce

1. Open menu and tap "Recorder" to open Recorder app
2. Go through the first time setup of account and backup and sync settings
3. Press "Record" button to start the recording; You can also switch tabs to the Live transcription tab to turn on the transcription feature

/device avicii
/version eleven_plus

**Comment by Jorg3Lucas** [comment]
Hello, I hope you're ok, unfortunately we don't support android 11 anymore and that's why we are closing the old issues, if the problem persists on android 12, please open a new issue
