### ISSUE TITLE
Huge battery drain  in lavender device

### ISSUE THREAD

**Issue by manab52425** [PixelExperience/android-issues#111]
## Build date

```
PixelExperience_Plus_lavender-11.0-20210526-1452-OFFICIAL
```

## Expected Behavior

```
A good battery backup

```

## Current Behavior

```
Lots of batteries running out in less time and only 4:00 - 4:30 hours battery on full charge.

```

## Possible Solution

```
An update should fix it

```

## Steps to Reproduce

```
1. Full charge your phone
2. Then use chrome, YouTube and Facebook for 45 minutes one by one 
3.
4.
```

/device lavender
/version eleven_plus
[logs.txt](https://github.com/PixelExperience/android-issues/files/6588526/logs.txt)
![Screenshot_20210528-142521_Settings](https://user-images.githubusercontent.com/84611056/120057904-a0aeb980-c064-11eb-80a8-57db10f2ccba.png)
![Screenshot_20210528-224037_Settings](https://user-images.githubusercontent.com/84611056/120057918-b7551080-c064-11eb-8f4c-640d0234d7cf.png)

![Screenshot_20210601-141940_Settings](https://user-images.githubusercontent.com/84611056/120295131-7d923d00-c2e4-11eb-9b24-37c87ffde3b9.png)

**Comment by faham1997** [comment]
This doesn't help . Provide logcat.

**Comment by manab52425** [comment]
Please fix battery draining issue on next June update.
![Screenshot_20210602-094112_Settings](https://user-images.githubusercontent.com/84611056/120425725-5a22cd00-c38c-11eb-80a4-49a9650f0791.png)
![Screenshot_20210602-095047_Settings](https://user-images.githubusercontent.com/84611056/120425733-5bec9080-c38c-11eb-84ef-7826df6ae354.png)

**Comment by manab52425** [comment]
> This doesn't help . Provide logcat.

Thnks for reply. Here is the logcat.
[logs.txt](https://github.com/PixelExperience/android-issues/files/6588522/logs.txt)
