### ISSUE TITLE
Flash rear camera cant use zenfone x00td

### ISSUE THREAD

**Issue by TrinxudasDoZe** [PixelExperience/android-issues#117]
## Build date

```
RQ2A.210505.003
PixelExperience_X00TD-11.0-20210518-0949-OFFICIAL
```

## Expected Behavior

```
When using the camera the rear camera should have flash just like the front camera does
```

## Current Behavior

```
The rear camera flash icon disappears,only the front camera has it
```

## Possible Solution

```
```

## Steps to Reproduce

```
1. Open up the camera app
2. Switch to rear camera if it isnt already
3. Flash button isn't visible
4.
```

/device X00TD
/version eleven

**Comment by Subinsmani** [comment]
Which kernel using?
List of all magisk modules using.....
And please report bug with logs atleast

**Comment by TrinxudasDoZe** [comment]
Kernel version  4.4.267-perf+ ( took it from droid info app )
Also logs [here](https://zerobin.net/?6307aa6ca2d46add#7fjo4Qd9VyogTlIMonNEL/fqiYSaLDo653w205SZsd4=)

**Comment by TrinxudasDoZe** [comment]
Front Camera:

![WhatsApp Image 2021-05-31 at 21 51 32](https://user-images.githubusercontent.com/24302790/120241386-8b9b7b80-c25a-11eb-8afd-14e793ae0a5f.jpeg)


Rear Camera ( No flash button )


![WhatsApp Image 2021-05-31 at 21 51 32 (1)](https://user-images.githubusercontent.com/24302790/120241387-8ccca880-c25a-11eb-982e-63cddb05cabc.jpeg)

**Comment by Subinsmani** [comment]
![photo_2021-05-31_21-52-36](https://user-images.githubusercontent.com/22902281/120255721-9eae4b80-c25a-11eb-9da9-fa5a76b1138f.jpg)
![photo_2021-05-31_21-52-41](https://user-images.githubusercontent.com/22902281/120255724-9fdf7880-c25a-11eb-9a36-6623b3f0d5af.jpg)



Here it is showing, please could you check to try on other camera applications like gcam.
And please restart your device once and check

**Comment by AsathalMannan** [comment]
flash icon there in both rear and front..!☑️

but for me, **front flash not working**..

- Not rooted
- Default Kernel
- Default Camera

**Comment by Subinsmani** [comment]
Flash only supports stock Asus camera.

**Comment by AsathalMannan** [comment]
> Front Flash only supports stock Asus camera.

oh alright!

**Comment by TrinxudasDoZe** [comment]
So i managed to find out what the issue is. If i turn on redeye reduction in camera settings it removes the flash icon, i didnt know that and i must've done it when i was all excited about installing this rom. Thank you !

**Comment by Subinsmani** [comment]
So i hope your issue get fixed. If yes then you can close this issue now.
