### ISSUE TITLE
Multiple CoC violations - OP7 series

### ISSUE THREAD

**Issue by baalajimaestro** [PixelExperience/android-issues#119]
## Build date
```
PixelExperience_guacamole-11.0-20210514-0944-OFFICIAL
```

## Expected Behavior
```
Builds shipped in-accordance with CoC
```

## Current Behavior
```
This is relevant to not just the Build date mentioned, it has existed in earlier builds too. And since OP7 series has a common tree, this exists in multiple devices too, inclusive of guacamole, hotdog, hotdogb and maybe even others I dont know of. I had spoken to one of the admins about the behavior earlier, with it going simply unheard. 

**Overlay of FOD icon:** https://github.com/PixelExperience-Devices/device_oneplus_sm8150-common/blob/eleven/overlay-aosp/frameworks/base/packages/SystemUI/res/drawable/fod_icon_default.xml

**Boeffla Wakelock Blocker:** This violates Kernel Guidelines mentioned under https://github.com/PixelExperience/docs/blob/master/kernel_guidelines.md

For the record, this commit exists on https://github.com/PixelExperience-Devices/kernel_oneplus_sm8150/commit/9c82f9ae1f9efacbb01f4be86df5f7e760e457b9

And has been shipped to users for possibly a month or even more.

This kernel also includes the efficient freqs which one of the admins called out when I shipped.

https://github.com/PixelExperience-Devices/kernel_oneplus_sm8150/commit/47c811e19e356ea304794a28f44e301a9efc9401
```

## Possible Solution
```
Remove them? Idk why the maintainer needs to overlay fod icon, or either ship Boeffla Blocker in the first place.
```

## Steps to Reproduce
```
There is nothing to reproduce here.
```
/device guacamole
/version eleven

**Comment by Chandra-Chaganti** [comment]
-> FOD icon change is not a part of COC(https://github.com/PixelExperience/docs/blob/master/maintainers_code_of_conduct.md).it's changed just for visual impression and I am ok to revert it, its better to add in COC then new maintainers will not change it.
-> Kernel commits agreed and it will be reverted in some time (before releasing new build)

**Comment by Hlcpereira** [comment]
About the FOD Icon matter, it would (and should) fall into one of the Device Requirements (https://github.com/PixelExperience/docs/blob/master/device_requirements.md) points:

"The device MUST NOT include any unused overlays and packages. This includes, but is not limited to, packages not being built, packages that don't work, obsolete packages, placebo 'tweaks' or any packages that will include unnecessary and/or unwanted features, as stated at the Maintainers Code of Conduct."

Although mainly used as a parameter during applications the Device Requirements would still be something implied even afterwards the application being accepted.

**Comment by Chandra-Chaganti** [comment]
above all points fixed
