### ISSUE TITLE
Screen share not working

### ISSUE THREAD

**Issue by sergiorgb** [PixelExperience/android-issues#126]
## Build date

```
PixelExperience_Plus_surya-11.0-20210521-0808-OFFICIAL
```

## Expected Behavior

```
it should share screen
```

## Current Behavior

```
I share screen to my tv then phone soft reboots
```

## Possible Solution

```
i dont know
```

## Steps to Reproduce

```
1. share screen to tv
2. then soft reboot

```

/device surya
/version eleven_plus

**Comment by Jorg3Lucas** [comment]
Unfortunately the device is no longer supported by the project as the old maintainer no longer owns the device.
