### ISSUE TITLE
Device code name is incorrect

### ISSUE THREAD

**Issue by Yash-javiya** [PixelExperience/android-issues#131]
## Build date

```
RQ2A.210505.003 PixelExperience_Plus_mido-11.0-20210514-2030-OFFICIAL
```

## Expected Behavior

```
My device code is mido 
```

## Current Behavior

```
Showing my device code : aosp_mido
```

## Possible Solution

```
Change device code from aosp_mido to mido 
```

## Steps to Reproduce

```
[Screenshot of issue](https://drive.google.com/file/d/1-U8gKztM7w0eW4I1fX_KIQav0ywoe9cD/view?usp=drivesdk) 
```

/device mido 
/version eleven_plus

**Comment by GiaSen** [comment]
That magisk module doesn't support mido, as stated in https://github.com/Magisk-Modules-Repo/WDAnimationcxair#supported-device-list

**Comment by jjpprrrr** [comment]
mido is not supported. It doesn't matter if it's aosp_mido or mido. You can see from the code that some devices actually have the aosp_ prefix.

https://github.com/Magisk-Modules-Repo/WDAnimationcxair/blob/master/common/unity_install.sh#L44

**Comment by jjpprrrr** [comment]
I believe the `aosp_`, `lineage_`, or `omni_` prefix is intentional. It is looking for a certain ROM, not a device in general.
