### ISSUE TITLE
Google Photos backup doesn't working

### ISSUE THREAD

**Issue by PilonietaHector** [PixelExperience/android-issues#1369]
## Build date

PixelExperience_ginkgo-12.0-20211221-2147-OFFICIAL

## Expected Behavior

The backup of the photos on Google Photos should be completed without temperature notices since the device is not hot.

## Current Behavior

Google Photos displays a notice that the device is too hot and does not back up

## Possible Solution

Check the API of the temperature sensors, may be corrupt

## Steps to Reproduce

1. Open Photos app
2. In backup status, the "device is too hot" warning is displayed

/device ginkgo
/version twelve

**Comment by PilonietaHector** [comment]
![Uploading Screenshot_20220112-195423_Fotos.png…]()

**Comment by PilonietaHector** [comment]
![Screenshot_20220112-195423_Fotos](https://user-images.githubusercontent.com/69775208/149249625-2a225adb-744d-49a7-8ead-38c4df60e55a.png)
Uploaded a screenshot with the issue, all apps are updated and before I clear cache and data of Photos an Google Play Services

**Comment by Pitrsak** [comment]
I've had the same issue, my fix was uninstalling Google one app, turning off backup of the phone, deleting the backup from Google drive and then turning it on again. If It doesn't work, try log out from Google photos and relogin again.

**Comment by PilonietaHector** [comment]
Updated solution: In initial setup, when Google One´s options are showed, must be skipped
