### ISSUE TITLE
Screen went black after connecting to external audio in Raphael

### ISSUE THREAD

**Issue by Hyperbeast-S** [PixelExperience/android-issues#1374]
## Build date

PixelExperience_raphael-12.0-20211231-1805-OFFICIAL.zip

## Expected Behavior

Headphones connected , Phone should be working normally

## Current Behavior

After connecting to external audio devices (TWS or wired headphones 🎧), screen freezes and went blank.

## Possible Solution

Reflash device problem solve for 1 day. Then problem starts again.

## Steps to Reproduce

1.Connect your mobile to any wired headphones or bluetooth headset
2.Wait for a second or two....
3.The screen will freeze.
4.If you lock and try to unlock it, the screen will be blank

/device raphael
/version twelve

**Comment by Hyperbeast-S** [comment]
Can you fix quickly

**Comment by ginkgobro** [comment]
Update gapps and clear system cache.....that should do....
