### ISSUE TITLE
Floating icon is not moving with auto-rotate screen

### ISSUE THREAD

**Issue by vipin55278** [PixelExperience/android-issues#173]
## Build date

```
PixelExperience_Plus_land-11.0-20210422-1521-OFFICIAL
```

## Expected Behavior

```
It should move with screen rotation to landscape. With manual rotation it work but not working with auto-rotate.
```

## Current Behavior

```
It is moving irregular.
```

## Possible Solution

```
With you tube it is working when manual rotation but not working with auto-rotate screen.
```

## Steps to Reproduce

```
1. Run game guardian and click start button.
2. Floating icon appears on screen.
3. Now run free fire.
4. You will see floating icon of game guardian will not move correctly.
```

/device land
/version eleven

**Comment by vipin55278** [comment]
I used rotation orientation manager it works and forced auto rotate.

**Comment by jhenrique09** [comment]
That is app side issue.

**Comment by vipin55278** [comment]
It is not app side issue.  App is working in other mobile with stock rom
android 11. It was working fine with miui and havoc os.
If you can't admit it just not say "this is app side issue".

**Comment by vipin55278** [comment]
Plz admit that you can't or don't bother çoz of small issue. It is orientation problem bro.
