### ISSUE TITLE
VoLTE not working on potter devices

### ISSUE THREAD

**Issue by anandjosetherakam** [PixelExperience/android-issues#177]
## Build date

```
RQ2A.210505.003
PixelExperience_Plus_potter-11.0-20210514-0432-OFFICIAL
```

## Expected Behavior

```
I should be able to call , send and receive SMS using VoLTE (JIO Sim) when VoLTE is enabled in the settings
Also, VoLTE logo should appear in the status bar when mobile data is turned on
```

## Current Behavior

```
Not able to make phone calls, send or receive text messages from a VoLTE(Jio) Network. I am able to get a mobile data connection and the range is also shown.
```

## Possible Solution

```
Fix VoLTE connection
```

## Steps to Reproduce

```
1. Use a VoLTE enabled SIM , preferably Jio SIM and enable Mobile Data
2. Enable VoLTE from Settings--> Network--> SIM1--> Advanced
3. When a call is placed it immediately ends.
```

/device potter
/version eleven_plus

**Comment by jjpprrrr** [comment]
Just FYI, PE does not display a VoLTE icon in status bar.

**Comment by zjunior06** [comment]
Just delere "persist.vendor.radio.jbims=1" from build.prop and reboot!

**Comment by anandjosetherakam** [comment]
> Just delere "persist.vendor.radio.jbims=1" from build.prop and reboot!

Removed the code from built.prop and rebooted
Still facing the same issue.

**Comment by zjunior06** [comment]
Which operator?

**Comment by anandjosetherakam** [comment]
> Which operator?

JIO

**Comment by zjunior06** [comment]
U not have telegram? Its better for support things like this

**Comment by anandjosetherakam** [comment]
> U not have telegram? Its better for support things like this

I raised the issue in PE telegram group, found multiple people facing the same issue.

**Comment by zjunior06** [comment]
> > U not have telegram? Its better for support things like this
> 
> I raised the issue in PE telegram group, found multiple people facing the same issue.

Join potter group:
https://t.me/potterofficial here you will receive better support for this.

**Comment by anandjosetherakam** [comment]
The issue has been resolved. 
The device was flashed to the Stock ROM(Nougat) and I noticed that the IMEI was set to 0. Fixed that issue as per [https://forum.xda-developers.com/t/fix-persist-resolve-imei-0-volte-4g-explanation-requirements.3825147/]. Updated my ROM back to Pixel Experience and VoLTE started working again
