### ISSUE TITLE
can't make calls or receive them after latest update. Also can't set fingerprint.

### ISSUE THREAD

**Issue by sepoliur** [PixelExperience/android-issues#1834]
## Build date

PixelExperience_kebab-12.0-20220225-1956-OFFICIAL.zip

## Expected Behavior

calls should work normally and should be able to set fingerprint unlock

## Current Behavior

When i make a call of receive one over SIM card or whatsapp or any other platform, an annoying and continuous beeping sound starts and ends as soon as i end the call.
This only started to happen after i updated to the latest build over the air.

## Possible Solution

Don't really know, but this is what i already tried without good results:
- formatting data/factory reset
- flashing previous release
- changing SIM card network bands
- removing and putting back SIM card on phone

## Steps to Reproduce

1. Try to set Fingerprint unlock
2. Try to make a call or receive one

/device kebab
/version twelve

**Comment by Hasaber8** [comment]
Please try the latest build and be sure to e on latest OOS 11 and not 12.
Reopen the issue if the issue persists
