### ISSUE TITLE
PE+ LiveDisplay not showing full settings.

### ISSUE THREAD

**Issue by mrfinster** [PixelExperience/android-issues#184]
## Build date

```
PixelExperience_Plus_enchilada-11.0-20210602-0712-OFFICIAL
```

## Expected Behavior

```
When opening LiveDisplay in settings, all options should be available such as color profile, display mode, color calibration etc.
```

## Current Behavior

```
The LiveDisplay only shows the picture adjustment options and nothing else.
```

## Possible Solution

```
No idea at the moment
```

## Steps to Reproduce

```
1. Open Settings
2. Open Display
3. Open LiveDisplay
4. Options are missing
```

/device enchilada 
/version eleven_plus

**Comment by SevralT** [comment]
Yes! I know. I dropped it in first release. Wait for it in next update.

**Comment by mrfinster** [comment]
Hey! Hope you're well. Not trying to ask for any ETA but is it possible to know what the update cycle for Pixel Experience is? Do you guys release updates once a month?

**Comment by Hlcpereira** [comment]
About this issue: It's not considered a bug, therefor closed.

About the release window, the maintainers are obligated to release non-Plus builds monthly. Plus Edition builds are purely optional, therefor not having any sort of enforcement for updates for such. All this stated in our Code of Conduct.
