### ISSUE TITLE
SIM is enabling automatically in Poco f1  after device restart

### ISSUE THREAD

**Issue by tarunsamal** [PixelExperience/android-issues#199]
---
name: SIM is enabling automatically in Poco f1  after device restart
about: I have disabled my secondary SIM in PixelExperience_Plus_beryllium-11.0-20210519-0726-OFFICIAL rom , but once I restart the device its SIM2 is getting enabled automatically.
title: SIM is enabling automatically in Poco f1 after device restart
---

## Build date

```
PixelExperience_Plus_beryllium-11.0-20210519-0726-OFFICIAL
```

## Expected Behavior

```
Sim should stay disabled even after restart
```

## Current Behavior

```
Sim is disabled in settings , phone is restarted , sim is enabled automatically
```

## Possible Solution

```
```

## Steps to Reproduce

```
1. insert two sim in the phone
2. disbled the secondary sim
3. reboot the device
4.
```

/device beryllium
/version eleven_plus

**Comment by jjpprrrr** [comment]
It has been a known issue for several months. If you have a solution, you are welcome to submit a PR (if it's on the device side) or push to PE gerrit.
