### ISSUE TITLE
FM Radio picking sound from local microphone

### ISSUE THREAD

**Issue by Sahil-Desu** [PixelExperience/android-issues#202]
## Build date

```
Example: PixelExperience_Plus_potter-11.0-20210514-0432-OFFICIAL.zip
```

## Expected Behavior

```
FM Radio should play FM.
```

## Current Behavior

```
FM Radio picks up the local surrounding sound now and plays it on earphone with delay.
```

## Possible Solution

```
```

## Steps to Reproduce

```
1. Connect Earphone.
2. Open FM Radio. Select any frequency.
3. Hear local mic sound instead of FM.
4.
```

/device potter
/version eleven_plus

**Comment by zjunior06** [comment]
Anything wrong, not happeb

> ## Build date
> ```
> Example: PixelExperience_Plus_potter-11.0-20210514-0432-OFFICIAL.zip
> ```
> 
> ## Expected Behavior
> ```
> FM Radio should play FM.
> ```
> 
> ## Current Behavior
> ```
> FM Radio picks up the local surrounding sound now and plays it on earphone with delay.
> ```
> 
> ## Possible Solution
> ## Steps to Reproduce
> ```
> 1. Connect Earphone.
> 2. Open FM Radio. Select any frequency.
> 3. Hear local mic sound instead of FM.
> 4.
> ```
> 
> /device potter
> /version eleven_plus

Anything wrong, not happening here. But try disable Google Assistant.

**Comment by Sahil-Desu** [comment]
Yes, the FM Radio is working after disabling the assistant, but can you please figure something that I won't have to disable the assistant every time I've to use the radio. Thanks for replying. Have a great day!

**Comment by Jorg3Lucas** [comment]
issue fixed
