### ISSUE TITLE
Merge Android security bulletin 

### ISSUE THREAD

**Issue by maluueu** [PixelExperience/android-issues#206]
## Build date

```
Example: PixelExperience_Plus_monet-11.0-20210613-1346-UNOFFICIAL
```

## Expected Behavior

```
Android security bulletin should be June
```

## Current Behavior

```
Still seeing Android security bulletin from Mai
```

## Possible Solution

```
Merge Android security bulletin into source
```

## Steps to Reproduce

```
1. Build
2. Check Android security bulletin version (date)
3.
4.
```

/device apollo
/version eleven_plus

**Comment by jjpprrrr** [comment]
June security patch has been merged already. Your build name says monet but your /device says apollo. Please refrain from submitting issues like this.
