### ISSUE TITLE
Wrong location navigation pill

### ISSUE THREAD

**Issue by tqthinh16** [PixelExperience/android-issues#2063]
## Build date

PixelExperience_miatoll-12.0-20220224-0430-OFFICIAL

## Expected Behavior

Navigation pill (full screen gesture) should be located at the bottom of the screen.

## Current Behavior

Navigation pill in some cases has wrong locations (i.e stay on the screen edges after rotating/ returning to home screen).

## Possible Solution

Edit here

## Steps to Reproduce

1. Open any app like games in landscape mode (but don't enable screen rotation)
2. Go to switch app mode (recent apps).
3. Select a app icon and choose "App info"
4. In the setting screen, the pill keep staying on the edge

/device miatoll
/version twelve

**Comment by jhenrique09** [comment]
know issue on Android 12L, it's Google fault, there's no fix for now
