### ISSUE TITLE
Microphone issues on VoIP calls

### ISSUE THREAD

**Issue by zurabi97** [PixelExperience/android-issues#25]
## Build date

```
PixelExperience_Plus_ginkgo-11.0-20210424-1911-OFFICIAL
```

## Expected Behavior

```
When I make a call on VoIP app, microphone does not work for some seconds or a minute. Also, after a VoIP call, multimedia playback is a bit low. 
```

## Current Behavior

```
Not working mic for some seconds or a minute. Low multimedia volume after VoIP call.
```

## Possible Solution

```
Restart, to fix the low multimedia volume
```

## Steps to Reproduce

```
1. Open VoIP app (WhatsApp, Viber etc.).
2. Make a call.
3. The person cannot hear me for some seconds or minute.
4. After, the person can hear me.
5. Sometimes, after a videocall, there is low multimedia volume.
```

/device ginkgo
/version eleven_plus

**Comment by zurabi97** [comment]
Logcat:
[logcat.txt](https://github.com/PixelExperience/android-issues/files/6410374/logcat.txt)

**Comment by danascape** [comment]
Will look into it

**Comment by danascape** [comment]
I know about it already m

**Comment by zurabi97** [comment]
Did a mistake on multimedia low volume, it happen after someone call me via VoIP app. 
Also, if they call me via VoIP, the mic work instantly.

**Comment by Joskabacsi** [comment]
Do you need another logcat for the analysis?

**Comment by danascape** [comment]
> Do you need another logcat for the analysis?

nope.

**Comment by danascape** [comment]
> Did a mistake on multimedia low volume, it happen after someone call me via VoIP app.
> Also, if they call me via VoIP, the mic work instantly.

alright.

**Comment by Joskabacsi** [comment]
I have the same issue what you described before. The viber call builds up but no mic. GSM call is ok. Zello talk is ok. So no mic problem.
[logcat.txt](https://github.com/PixelExperience/android-issues/files/6491921/logcat.txt)

**Comment by Jon2814** [comment]
The same issue is happening with Redmi Note 7s
(PixelExperience_lavender-11.0-20210522-1047-OFFICIAL)
and having problems with selection text or file taking longer time
[logcat.txt](https://github.com/PixelExperience/android-issues/files/6584750/logcat.txt)


Plz look forward and help me

**Comment by zurabi97** [comment]
Seems the mic issue is being fixed on June's build with new device trees.

**Comment by Jon2814** [comment]
No still i am facing
