### ISSUE TITLE
When the notch is set to hide and background blur is enabled, the UI shifts

### ISSUE THREAD

**Issue by i-force-quit** [PixelExperience/android-issues#256]
## Build date

```
RQ3A.210605.005
PixelExperience_Plus_beryllium-11.0-20210622-0854-OFFICIAL

```

## Expected Behavior

```
Ui should behave normally, with no ui shifting or black bars on the bottom.
```

## Current Behavior

```
When the notch is set to hide and background blur is enabled, the entire system UI moves when using guesture or simply trying to access the notification panel; this only occurs after the phone is rebooted.

```

## Possible Solution

```

```

## Steps to Reproduce

```
1. Hide notch from display settings or developer options
2. Enable background blur from developer options
3. Reboot 
4. Try to access notification panel or try to use navigation gesture
```

/device beryllium
/version eleven_plus

**Comment by i-force-quit** [comment]
I found the same bug in lavender and dipper
[before reboot.txt](https://github.com/PixelExperience/android-issues/files/6718376/before.reboot.txt)
[after reboot.txt](https://github.com/PixelExperience/android-issues/files/6718390/after.reboot.txt)

**Comment by jjpprrrr** [comment]
Quoting issue https://github.com/PixelExperience/android-issues/issues/30

`We don't support blur oficially, so don't expect a fix for that`

**Comment by i-force-quit** [comment]
I'm aware that blur is an experimental feature 😊
