### ISSUE TITLE
exfat filesystems are not supported, so I can't use my SD card.

### ISSUE THREAD

**Issue by mr-pi12** [PixelExperience/android-issues#2572]
## Build date

PixelExperience_Plus_renoir-12.1-20220426-0811-OFFICIAL

## Expected Behavior

System should be able to recognise the SD card I used to backup my data formatted to exfat

## Current Behavior

Pixel Experience only supports fat32, unlike the stock rom, and means I can't restore my backed up data because of its 4GB file size limit.

## Possible Solution

To add support for exfat or filesystems outside of fat32.

## Steps to Reproduce

1.Insert SD card with exfat filesystem
2.Check files app to see if system can read data

/device renoir
/version twelve_plus

**Comment by ArixElo** [comment]
From the next build there will be added.

**Comment by mr-pi12** [comment]
> From the next build there will be added.

thanks, that would be really helpful!

**Comment by ArixElo** [comment]
> > From the next build there will be added.
> 
> thanks, that would be really helpful!

https://github.com/PixelExperience-Devices/kernel_xiaomi_sm7350/commit/3659f937002e2fbdaf5e9b2dcb37c0a956c0ef4f
change added, from the next build exFAT and NTFS will work.

**Comment by mr-pi12** [comment]
👍

**Comment by mr-pi12** [comment]
> > > From the next build there will be added.
> > 
> > 
> > thanks, that would be really helpful!
> 
> [PixelExperience-Devices/kernel_xiaomi_sm7350@3659f93](https://github.com/PixelExperience-Devices/kernel_xiaomi_sm7350/commit/3659f937002e2fbdaf5e9b2dcb37c0a956c0ef4f) change added, from the next build exFAT and NTFS will work.

I installed the latest build yesterday, but the system is still unable to recognise the exfat filesystem and believes it to be corrupted. Is there something wrong on my end?

**Comment by mr-pi12** [comment]
@ArixElo

**Comment by ArixElo** [comment]
> > > > From the next build there will be added.
> > > 
> > > 
> > > thanks, that would be really helpful!
> > 
> > 
> > [PixelExperience-Devices/kernel_xiaomi_sm7350@3659f93](https://github.com/PixelExperience-Devices/kernel_xiaomi_sm7350/commit/3659f937002e2fbdaf5e9b2dcb37c0a956c0ef4f) change added, from the next build exFAT and NTFS will work.
> 
> I installed the latest build yesterday, but the system is still unable to recognise the exfat filesystem and believes it to be corrupted. Is there something wrong on my end?

Can you give me a log when you try to use your pendrive?

**Comment by mr-pi12** [comment]
How would I create a log?

**Comment by ArixElo** [comment]
> How would I create a log?

There are tutorials on the Internet how to do that.

**Comment by mr-pi12** [comment]
> > How would I create a log?
> 
> There are tutorials on the Internet how to do that.

Sorry for the really late reply, I've been caught up in exams, but aren't there different types of logs - which do you need for this issue?

**Comment by ArixElo** [comment]
I do require only two of them: logcat & dmesg, and you need to do them while you try to use your exFAT/NTFS device.

**Comment by mr-pi12** [comment]
So I should enable the logging and try to insert the sd card, right?

**Comment by ArixElo** [comment]
> So I should enable the logging and try to insert the sd card, right?

Yes, and after that send me the files.

**Comment by mr-pi12** [comment]
I don't know if I did it right, but here are the log files I got.
[dmesg.log](https://github.com/PixelExperience/android-issues/files/8850702/dmesg.log)
[logcat.txt](https://github.com/PixelExperience/android-issues/files/8850703/logcat.txt)

**Comment by mr-pi12** [comment]
@ArixElo did I record the log files wrong?
