### ISSUE TITLE
Charging time issue

### ISSUE THREAD

**Issue by daniele0** [PixelExperience/android-issues#279]
## Build date

```
PixelExperience_Plus_avicii-11.0-20210622-0619-OFFICIAL
```

## Expected Behavior

```
Showing up the right charging time remaining when plug in the smartphone
```

## Current Behavior

```
It says "1 minute remaining" (even if the battery percentage is 2%) or "22 hours remaining" (even if the battery percentage is 90% with speed charging)
```

## Possible Solution

```
I don't know
```

## Steps to Reproduce

```
1. Plug in you phone for charging it;
2. See the remaining charging time at the bottom;
```

/device avicii
/version eleven_plus

**Comment by daniele0** [comment]
[livedisplay.txt](https://github.com/PixelExperience/android-issues/files/6748699/livedisplay.txt)

**Comment by daniele0** [comment]
![Screenshot_20210708-205158](https://user-images.githubusercontent.com/57802982/124975654-85a17300-e02e-11eb-8f6e-af6aaa7a9a55.png)

**Comment by KakatkarAkshay** [comment]
I'm using OnePlus vendor so I cannot modify vendor.img, there's nothing I can do about this for now and this is not a critical issue.
