### ISSUE TITLE
Fingerprint scanner with NightLight on

### ISSUE THREAD

**Issue by alexprasetia** [PixelExperience/android-issues#280]
## Build date

```
PixelExperience_Plus_raphael-11.0-20210629-0320-OFFICIAL.zip
```

## Expected Behavior

```
Nightlight still on during fingerprint scanning. 
```

## Current Behavior

```
This cause fingerprint always not accurate 
```

## Possible Solution

```
On stock ROM, nightlight will be off in lock screen or during fingerprint scanning. Thus, it will not affect the accuracy.
```

## Steps to Reproduce

```
1. Register fingerprint
2. Turn on nightlight
3. lock the screen
4. try to do fingerprint scanning
```

/device raphael
/version eleven_plus

**Comment by Jorg3Lucas** [comment]
I believe it has already been fixed, it is working in the build released today but there is still no way to automatically disable the night light, I will be bringing this possibility as soon as possible
