### ISSUE TITLE
Under display fingerprint scanner logo and light location move on screen auto rotate

### ISSUE THREAD

**Issue by alexprasetia** [PixelExperience/android-issues#282]
## Build date

```
PixelExperience_Plus_raphael-11.0-20210629-0320-OFFICIAL.zip
```

## Expected Behavior

```
The fingerprint logo and light should have stayed in on the fingerprint sensor position
```

## Current Behavior

```
when auto rotate is on and home screen rotated then turning off the screen, the fingerprint logo will be moved to the right on the always on display or raise to wake screen. When area on the fingerprint sensor is touched, no light will turn on. However, when the fingerprint logo on the right is touched, the light turn on beneath the logo.
```

## Possible Solution

```
Probably excluding the logo from the auto rotate function.
```

## Steps to Reproduce

```
1. Turn on raise to wake or double tap to wake
2. Turn on autorotate
3. Rotate the screen
4. Lock the screen
5. Double tap or raise to wake,
6. The fingerprint logo will be moved
```

/device raphael
/version eleven_plus

**Comment by Jorg3Lucas** [comment]
I can't reproduce it as it doesn't happen here following the reproduction steps

**Comment by alexprasetia** [comment]
understand, when it happen again, i will provide the log file,
thank you for your support!

**Comment by alexprasetia** [comment]
Hi Jorg3Lucas,
I found that when the screen is locked during rotation animation will trigger this issue.
it will have higher chance of appearing when the transition animation is set to be lower than 1.0x (in my case, i tried 0.6x and 0.2x)

[logcat.txt](https://github.com/PixelExperience/android-issues/files/6794494/logcat.txt)

/device raphael
/version eleven_plus
