### ISSUE TITLE
Google assistant doesn't show

### ISSUE THREAD

**Issue by daniele0** [PixelExperience/android-issues#287]
## Build date

```
PixelExperience_Plus_avicii-11.0-20210622-0619-OFFICIAL
```

## Expected Behavior

```
When I call the Google Assistant, it should appear the classic window
```

## Current Behavior

```
That window doesn't appear
```

## Possible Solution

```
I don't know
```

## Steps to Reproduce

```
1. Call Google Assistant, or slide from the edge of the phone
```

/device avicii 
/version eleven_plus

**Comment by KakatkarAkshay** [comment]
I cannot reproduce this issue, it works just fine for me.

**Comment by daniele0** [comment]
Did you try to say "Hey Google"? Especially with an app opened?

**Comment by KakatkarAkshay** [comment]
Yes

**Comment by Jorg3Lucas** [comment]
> I cannot reproduce this issue, it works just fine for me.

its google app issue ig

**Comment by Iamviju4229563** [comment]
Iam also facing this issue

**Comment by KakatkarAkshay** [comment]
Was fixed few days ago with Google app update
