### ISSUE TITLE
Authy doesn't detect any biometrics configured even if I have Face Unlock enabled 

### ISSUE THREAD

**Issue by pGbSean** [PixelExperience/android-issues#2891]
## Build date

PixelExperience_Plus_sunfish-12.1-20220620-0402-OFFICIAL

## Expected Behavior

Authy doesn't detect that I have Face Unlock enabled

## Current Behavior

Authy should detect that I have Face Unlock enabled so that I can unlock the app with my face to view the codes

## Possible Solution

Maybe some tweaking to the Face Unlock code?

## Steps to Reproduce

1. Get your Face Unlock enabled on Pixel 4a
2. Go to Authy
3. Settings > App Protection > Enable Biometrics
4. Authy says that there are no biometrics configured in your device

/device sunfish
/version twelve_plus

**Comment by jhenrique09** [comment]
some apps doesn't works well when Face Unlock exposed, that is a desired behavior.
