### ISSUE TITLE
No sounds from device (even alarms)!!!!

### ISSUE THREAD

**Issue by TheCruzJ4v5** [PixelExperience/android-issues#291]
## Build date

```
"PixelExperience Plus beryllium-11.
0-20210622-0854-OFFICIAL.zip"
```

## Expected Behavior

```
Sounds should come from device.
```

## Current Behavior

```
Sound automatically drops to 0% when media is played on a bluetooth device and no sound coming from speaker of the device when the Bluetooth is disconnected. No sounds even notification sounds coming from device. Recorder doesn't work anywhere.
```

## Possible Solution

```
1. It's a software bug because I tried flashing stock ROM and it worked fine.
2. Some apps were also crashing so I asked a developer(Hendrik rydgard) he told me that openSlinit was crashing for his app.
```

## Steps to Reproduce

```
1.https://photos.app.goo.gl/qYh4NDqGGGhY1bqy8
2.https://docs.google.com/document/d/1iW0xcPavEoD5KoOS5L9qaaJBCy6Xy61PgNdHtdXDrzM/edit?usp=drivesdk
3. System logs👆👆
4.i had posted the same issue in June also. Developers please look into it. ☺️

```

/device beryllium
/version eleven_plus

**Comment by lakgarg** [comment]
duplicated #97

**Comment by TheCruzJ4v5** [comment]
can you please tell me what this means, because I'm new to this stuff
#https://photos.app.goo.gl/3UMQ9UPfK6d5rwUi6
P.S thanks a lot for responding 😊

**Comment by jjpprrrr** [comment]
> can you please tell me what this means, because I'm new to this stuff
> #https://photos.app.goo.gl/3UMQ9UPfK6d5rwUi6
> P.S thanks a lot for responding 😊

Your audio HAL failed to start, possibly due to missing/broken audio configs, like mixer_path_*.xml and other files.

Closing the issue because there is no way it is from the ROM side.

**Comment by TheCruzJ4v5** [comment]
Yeah ok.
Can you please tell me how do I fix this or I can't?
Thanks again😁

**Comment by jjpprrrr** [comment]
> Yeah ok.
> Can you please tell me how do I fix this or I can't?
> Thanks again😁

If it is truly like you said that you've never used any modules or modifications, this would not happen at all. Therefore, the best suggestion I can give you is to clean flash without using any mods.

**Comment by TheCruzJ4v5** [comment]
Dear sir,
I promise I hadn't rooted or used any modification for the past 3 months.
I clean flashed thrice during the month of April and still then even just after a clean flash the alarm or call sounds wouldn't work.
Promise
