### ISSUE TITLE
BSG cameras have stopped working in latest build

### ISSUE THREAD

**Issue by aravindvnair99** [PixelExperience/android-issues#297]
## Build date

```
PixelExperience_Plus_beryllium-11.0-20210622-0854-OFFICIAL
```

## Expected Behavior

```
The camera app should be working
```

## Current Behavior

```
The camera app either crashes or shows it's processing HDR forever. Sometimes only video mode is working. In previous builds, it's working perfectly fine.
```

## Possible Solution

```
Not sure what's going wrong to give a solution.
```

## Steps to Reproduce

```
1. Install any app from https://www.celsoazevedo.com/files/android/google-camera/dev-bsg/
2. Click a picture.
```

/device beryllium
/version eleven_plus

**Comment by cyberelon** [comment]
This bug has been fixed in internal test builds, so please use Parrot Cam for the time being until a bug fix build or July build is released.

**Comment by aravindvnair99** [comment]
> This bug has been fixed in internal test builds, so please use Parrot Cam for the time being until a bug fix build or July build is released.

Sure, will wait for the patch to arrive. Thanks for the update @cyberelon! :)

**Comment by aravindvnair99** [comment]
Was not working in June build but is working in July build. Hence closing the issue as it has been resolved.
