### ISSUE TITLE
Notification history button in notification shade is missing when there are no notifications

### ISSUE THREAD

**Issue by austingeorge1111** [PixelExperience/android-issues#303]
## Build date

```
PixelExperience_Plus_raphael-11.0-20210629-0320-OFFICIAL
```

## Expected Behavior

```
The notification history button should appear on the left of 'no notification' message, below the controls, in the notification shade when it is empty.
```

## Current Behavior

```
Visually, the notification history button is missing. However on tapping the blank area where it is supposed to be it does open up notification history.
```

## Possible Solution

```

```

## Steps to Reproduce

```
1. Enable notification history from settings -> apps and notifications -> notifications -> notification history
2. Make sure notification shade is empty; no notifications should remain in the notification shade
3. Notification history button should be missing
```

/device raphael
/version eleven_plus

**Comment by ayushrhll** [comment]
It's not a bug, click no "No notification" , it will navigate you to notification history.

**Comment by Jorg3Lucas** [comment]
> ## Build date
> ```
> PixelExperience_Plus_raphael-11.0-20210629-0320-OFFICIAL
> ```
> 
> ## Expected Behavior
> ```
> The notification history button should appear on the left of 'no notification' message, below the controls, in the notification shade when it is empty.
> ```
> 
> ## Current Behavior
> ```
> Visually, the notification history button is missing. However on tapping the blank area where it is supposed to be it does open up notification history.
> ```
> 
> ## Possible Solution
> ```
> 
> ```
> 
> ## Steps to Reproduce
> ```
> 1. Enable notification history from settings -> apps and notifications -> notifications -> notification history
> 2. Make sure notification shade is empty; no notifications should remain in the notification shade
> 3. Notification history button should be missing
> ```
> 
> /device raphael
> /version eleven_plus

Hi, as explained above, this is not a bug but a feature that becomes available after activating the history
