### ISSUE TITLE
Device volume malfunctioning

### ISSUE THREAD

**Issue by manakbisht** [PixelExperience/android-issues#33]
[logcat.txt](https://github.com/PixelExperience/android-issues/files/6420641/logcat.txt)

## Build date

```
PixelExperience_Plus_beryllium-11.0-20210420-1257-OFFICIAL
```

## Expected Behavior

```
The volume should increase or decrease either through the volume buttons or through the sound settings.
```

## Current Behavior

```
Volume increases without any input. Sometimes the volume buttons don't work or need to be pressed repeatedly. At other times, after decreasing the volume using the volume down button, the system increases the volume again on its own.
```

## Possible Solution

```
This bug does not exist in the stock MIUI 12 ROM. Checked after flashing the stock ROM on the same device.
```

## Steps to Reproduce

```
Occurs all the time even immediately after rebooting. Sometimes on just squeezing the phone without pressing the buttons at all. Therefore, don't have exact steps to reproduce. However, the logcat file is attached.
```

/device beryllium
/version eleven_plus

**Comment by lakgarg** [comment]
"Bug" isn't reproduce-able here, kindly attach a logcat for the same.

**Comment by MaheshKingdom** [comment]
> "Bug" isn't reproduce-able here, kindly attach a logcat for the same.

https://github.com/PixelExperience/android-issues/files/6420641/logcat.txt

**Comment by lakgarg** [comment]
its perhaps a hardware problem, as volume buttons work perfectly for everyone else.
