### ISSUE TITLE
[Avicii] display frequency locked

### ISSUE THREAD

**Issue by mario4693** [PixelExperience/android-issues#333]
## Build date

```
Example: PixelExperience_Plus_avicii-11.0-20210622-0619-OFFICIAL.zip
```

## Expected Behavior

```
After setting 60hz as Display frequency and enable display frequency in developer options, the display should show 60

```

## Current Behavior

```
After setting 60hz as Display frequency and enable display frequency in developer options, the display show 90 even after a reboot.
![Screenshot_20210714-175426_Impostazioni](https://user-images.githubusercontent.com/6690423/125653412-3c65ab0d-840d-405b-9014-d74901e250e1.png)

```

## Possible Solution

```
No idea
```

## Steps to Reproduce

```
1. Start from display set to 90hz
2. Show display frequency from developer options
3. Set now display to 60hz
4. Display still show a green text with 90 as frequency
```

/device avicii
/version eleven_plus

**Comment by KakatkarAkshay** [comment]
Provide a logcat while setting refresh rate to 60 hz. Also list any magisk modules you use.

**Comment by mario4693** [comment]
Hi. I don't use any magisk module. I attach the logcat now.
[logcat.txt](https://github.com/PixelExperience/android-issues/files/6821263/logcat.txt)

**Comment by daniele0** [comment]
Also for me 60 Hz doesn't work

**Comment by KakatkarAkshay** [comment]
Will check it when I get time

**Comment by VadimBannikov** [comment]
Yeah ? I have oneplus nord and i have this problem too !!!! Fix it please !

**Comment by KakatkarAkshay** [comment]
> Yeah ? I have oneplus nord and i have this problem too !!!! Fix it please !

I have already said I'll take a look when I get time.

**Comment by VadimBannikov** [comment]
> > Ага ? У меня oneplus nord и у меня тоже есть эта проблема !!!! Исправьте пожалуйста!
> 
> Я уже сказал, что посмотрю, когда будет время.

I found one thing . If you turn on power saving mode , 60hz turning too .

**Comment by KakatkarAkshay** [comment]
Fixed on latest build.
