### ISSUE TITLE
Neither Google Camera nor GCam is working

### ISSUE THREAD

**Issue by austingeorge1111** [PixelExperience/android-issues#343]
## Build date

```
PixelExperience_Plus_raphael-11.0-20210715-2325-OFFICIAL
```

## Expected Behavior

```
Google Camera and GCam should work normally 
```

## Current Behavior

```
Google Camera is crashing and GCam is not working properly on the principal lens
```

## Possible Solution

```
No idea
```

## Steps to Reproduce

```
1. Install Google Camera or BSC GCam port
2. Open Google Camera or Gcam
3. Apps crashing or not working properly
```

/device raphael
/version eleven_plus

**Comment by Jorg3Lucas** [comment]
Hello, how are you? The issue has already been fixed and will be working normally in the August security patch

**Comment by austingeorge1111** [comment]
I am good Lucas, hope you're doing well. Thank you for resolving the issue. Much appreciated!
