### ISSUE TITLE
Minimum brightness is too high

### ISSUE THREAD

**Issue by rdrenedo** [PixelExperience/android-issues#344]
## Build date

```
PixelExperience_sweet-11.0-20210717-0307-OFFICIAL
```

## Expected Behavior

```
Brightness should work normally 
```

## Current Behavior

```
Minimum brightness is too high it should be lower
```

## Possible Solution

```
No idea
```

## Steps to Reproduce

```
1. Open settings and set brightness to minimum, or set auto brightness and adjust bar to minimum.
```

/device sweet
/version eleven

**Comment by Hit360D** [comment]
I too have this issue on Sweet, the workaround right now is to go to Settings>Live Display>Color Calibration and sliding the R G B sliders down. It isn't a solution ofcourse, but meanwhile it's the only option. Hope it gets fixed soon.

**Comment by ZIDAN44** [comment]
It will fixed in next update :D

**Comment by rdrenedo** [comment]
This issue has been fixed in the August build. I close the issue.

Thank you very much @ZIDAN44 !!! 🙂
