### ISSUE TITLE
Brief description of your problem

### ISSUE THREAD

**Issue by camilofc** [PixelExperience/android-issues#3550]
## Build date

PixelExperience_Plus_lava-12.1-20220816-0748-OFFICIAL

## Expected Behavior

- Phone call with normal speaker volume. 
- Volume sliders must low or high volume. 
- During a phone call, people on the other side must hear you clear in a normal volume, not in a low volume that they almost can't hear you.

## Current Behavior

This report is based on version 12, so maybe could be fixed on version 13.

1. Outgoing phone call
- People almost can't hear you. They say can hear but too low.
- when turning on the speaker, volume is too high
- When speaker turned on  volume control sliders for that call doesn't work (speaker volume remains too high)

2. Incoming phone call 
- Eerything works well

3. Data call (i.e WhatsApp call)
- Eerything works well

Tried everything but doesn't work. Rooted phone.

## Possible Solution

Edit here

## Steps to Reproduce

1. Make an outgoing call
2. The other person almost can't hear you
3. Turn on speaker
4. Volume is too high 
5. Move the phone call sliders, volume remains too high

/device lava
/version twelve_plus

**Comment by Arjunr3108** [comment]
Redmi 9 uses Helio G35
Redmi 9 prime and poco M2 uses Helio G80

**Comment by Arjunr3108** [comment]
Same Issue, same version, same device (Poco M2)
