### ISSUE TITLE
Assert failed: update_dynamic_partitions(package_extract_file("dynamic_partitions_op_list"))

### ISSUE THREAD

**Issue by Tequinox-Z** [PixelExperience/android-issues#3598]
Rom to flash:
- Pixel Experience 13 (BETA)
Device:
- Xiaomi Mix 2S (Polaris)
- MIUI 12
- 6/64GB
- Recovery: Oficial Pixel Experience Recovery

**Comment by bassely** [comment]
I have the same issue here. 
same device
Mi Mix 2S

**Comment by iamNCJ** [comment]
I solved my problem in [https://github.com/PixelExperience/android-issues/issues/3994](https://github.com/PixelExperience/android-issues/issues/3994), maybe you can check the solutions there.
