### ISSUE TITLE
Data encryption is broken

### ISSUE THREAD

**Issue by Zedasix** [PixelExperience/android-issues#365]
## Build date

```
PixelExperience_Plus_begonia-11.0-20210717-0310-OFFICIAL
```

## Expected Behavior

```
Data encryption does not work on the last version, encryption worked on the previous version.
```

## Current Behavior

```
data is not encrypted
```

## Possible Solution

```
data encryption worked in the previous version of Pixel experience (PixelExperience_Plus_begonia-11.0-20210514-0310-OFFICIAL)
```

## Steps to Reproduce

```
1.go to settings,
2.then security,
3.at the bottom "Encryption and identifiers"
4.press "encrypt the phone"
5.follow the process until the phone displays bugdroid, this is where it crashes
```

/device Begonia
/version eleven_plus
[monlog.txt](https://github.com/PixelExperience/android-issues/files/6864125/monlog.txt)

**Comment by TheMalachite** [comment]
Data encryption is disabled on latest build due to some reasons, it will be enabled back on next ones

**Comment by Zedasix** [comment]
> Data encryption is disabled on latest build due to some reasons, it will be enabled back on next ones

more than to wait for the next update ! (sympa ta photo de profil d'une vidéo de sheshounet 👍)

**Comment by avi-iz** [comment]
Was this fixed in the august update?

**Comment by Zedasix** [comment]
> Was this fixed in the august update?

yes
