### ISSUE TITLE
Issue in using PIP

### ISSUE THREAD

**Issue by bubai2000** [PixelExperience/android-issues#383]
## Build date

```
PixelExperience_Plus_violet-11.0-20210716-0242-OFFICIAL.zip
```

## Expected Behavior

```
From an app that supports PIP, if we switch to another app, the video keeps playing on a minimized window.
```

## Current Behavior

```
The minimized window is appearing and disappearing. No issue with the audio. After a fresh restart(reboot) the issue resolves temporarily. 
```

## Possible Solution

```
No idea.
```

## Steps to Reproduce

```
1. Open YouTube(or any other app that supports PIP
2. Play a video
3. Switch to any other app without pausing the video
4. Hope you will find the bug
```

/device violet
/version eleven_plus

**Comment by dasshubham762** [comment]
Directly switching to another app doesn't trigger the Picture in Picture mode. The home button should be pressed to trigger the PiP mode. 
Hope you understand.

![Screenshot_20210725-084803~2](https://user-images.githubusercontent.com/30361989/126886586-92ece43d-addc-4bd4-b16a-a9fc84b3cfa7.png)

**Comment by bubai2000** [comment]
allow me some moments to make a screen recording and I hope then you'll understand what the problem exactly is.

**Comment by yash020797** [comment]
same goes with me, after flashing this rom, my pc is unable to detect my phone to transfer files. In fact, I have tried both roms 11 and 11+ as well. Both have same issues
how can I solve it.

**Comment by Jorg3Lucas** [comment]
Hello, I hope you're ok, unfortunately we don't support android 11 anymore and that's why we are closing the old issues, if the problem persists on android 12, please open a new issue
