### ISSUE TITLE
EE UK shows LTE icon instead of 4G

### ISSUE THREAD

**Issue by TheJaffaMeme** [PixelExperience/android-issues#384]
## Build date
```
PixelExperience_avicii-11.0-20210715-1423-OFFICIAL
```

## Expected Behavior
```
EE UK should show a 4G icon instead of an LTE icon as that is what all other carriers show and use in the UK.
```

## Current Behavior
```
EE UK instead has an LTE data indicator and uses LTE when describing features such as VoLTE, rather than calling them 4G Calling
```

## Possible Solution
```
LineageOS had a similar issue and it appeared there were two carrier configs with EE, one fully configured correctly with 4G indicator and other preferences and another that was just blank leading to it showing the default LTE data indicator.
```

## Steps to Reproduce
```
1. Insert EE UK sim card (MCC 234 MNC 30)
2. Data indicator shows LTE instead of 4G
```

/device avicii
/version eleven

**Comment by KakatkarAkshay** [comment]
The 4G/LTE icon is nothing but customisation. It just shows which network is being used. It's rom specific and cannot be considered a bug.

**Comment by TheJaffaMeme** [comment]
But I'm not talking about customising the icon the carrier config is literally incorrect and needs to be fixed with the correct one. It already exists just targets the wrong MCC and MNC.

**Comment by KakatkarAkshay** [comment]
> But I'm not talking about customising the icon the carrier config is literally incorrect and needs to be fixed with the correct one. It already exists just targets the wrong MCC and MNC.

It doesn't affect anything in terms of performance so for now I'll not be working on it. I'll take a look when I rebase trees
