### ISSUE TITLE
Battery Drain while idle (begonia)

### ISSUE THREAD

**Issue by compassnet** [PixelExperience/android-issues#388]
## Build date

```
PixelExperience_Plus_begonia-11.0-20210717-0310-OFFICIAL.zip
```

## Expected Behavior

```
Normal battery drain while idle (WiFi on, Data off, Battery Saver mode off, Location off, Bluetooth off, Digital Wellbeing off; depends on a lot of factors; my device is around 9 months old).
```

## Current Behavior

```
Battery Drain while the phone is idle (around 1% to 2% per hour).
The previous version of Pixel Experience did not drain the battery like this.
```

## Possible Solution

```
Turning off WiFi and enabling normal (not extreme) Battery Saver mode seems to drain the battery as expected.
Battery Saver mode is not optimal (no notifications for example). I usually only use it when sleeping or being away for extended periods of time.
```

## Steps to Reproduce

```
1. https://forum.xda-developers.com/t/rom-11-begonia-pixel-experience-official-aosp.4196041/post-85380955
2. If you check the screenshots from the link above you'll notice that the drain isn't caused by an application. It's something in System.
3. To be honest I do have Magisk installed with only one module (Systemless Hosts). I hope this doesn't invalidate my issue.
```

/device begonia
/version eleven_plus

[gsam_log.txt](https://github.com/PixelExperience/android-issues/files/6895266/gsam_log.txt)
[logcat.txt](https://github.com/PixelExperience/android-issues/files/6895381/logcat.txt)

**Comment by ZIDAN44** [comment]
Its happening as I am using prebuild kernel from miui 12.5 and yeah even on miui 12.5 battery drain too much high. So wait for xiaomi to give us kernel source.

**Comment by compassnet** [comment]
> Its happening as I am using prebuild kernel from miui 12.5 and yeah even on miui 12.5 battery drain too much high. So wait for xiaomi to give us kernel source.

I'm definitely not switching to another ROM because of this issue, so my options as I see them are the following:

1. Roll back to a previous version of Pixel Experience (which also means rolling back to their respective issues);
2. Keeping "Batter Saver" on;
3. Anything I didn't think of.

I've chosen #2 for now while also reading its drawbacks.

As for if and when Xiaomi will release the kernel source code I'll just keep my fingers crossed.

I love your work and thanks for the reply.

**Comment by Nicofisi** [comment]
I see this issue is now closed - has it been fixed?

**Comment by compassnet** [comment]
With this issue closed is this bug fixed?

**Comment by khan7860** [comment]
The battery drain is still present
It drains almost 15-20% while idling (7-8 hours)
screen brightness is at lowest and Wifi, mobile data, gps, sync, almost everything turned off.

Battery saver is turned on still I haven't seen any improvement

**Comment by Nicofisi** [comment]
@ refreshing
