### ISSUE TITLE
Bluetooth not turning on few seconds after airplane mode is enabled

### ISSUE THREAD

**Issue by cl-ement05** [PixelExperience/android-issues#412]
## Build date

```
RQ3A.210705.001
PixelExperience_dipper-11.0-20210717-2147-OFFICIAL
```

## Expected Behavior

```
Bluetooth should turn on as usual
```

## Current Behavior

```
Bluetooth fails to start for the next 10sec after airplane mode was enabled. After these 10sec, Bluetooth can be turned back on
I made a screen record : https://photos.app.goo.gl/HiymPd7qjmSGCUGa6
```

## Possible Solution

```
No idea sorry
```

## Steps to Reproduce

```
1. Make sure airplane mode is off and that at least wifi and Bluetooth are on
2. Turn on airplane mode in quick settings
3. Shortly after this, turn on Bluetooth
```

/device dipper
/version eleven

**Comment by GiaSen** [comment]
Yeah the issue is there, and it happens on my device as well, runnning the Plus version

**Comment by Jorg3Lucas** [comment]
Hello, I hope you're ok, unfortunately we don't support android 11 anymore and that's why we are closing the old issues, if the problem persists on android 12, please open a new issue
