### ISSUE TITLE
Type-C wired headphones causes heat and drains battery

### ISSUE THREAD

**Issue by Ma-Asg** [PixelExperience/android-issues#4129]
## Build date

PixelExperience_Plus_guacamoleb-13.0-20221112-1213-OFFICIAL

## Expected Behavior

Type-C wired headphone work as it should be

## Current Behavior

When connecting wired headphone via Type-C socket, a charging notification appears and after playing music file for a while causes the phone to heat up and drain battery quickly

## Possible Solution

no idea

## Steps to Reproduce

1. Connect a type-c wired headphone
2. play a file to produce sound through headphone

/device guacamoleb
/version thirteen_plus

**Comment by shantanu-sarkar** [comment]
> ## Build date
> PixelExperience_Plus_guacamoleb-13.0-20221112-1213-OFFICIAL
> 
> ## Expected Behavior
> Type-C wired headphone work as it should be
> 
> ## Current Behavior
> When connecting wired headphone via Type-C socket, a charging notification appears and after playing music file for a while causes the phone to heat up and drain battery quickly
> 
> ## Possible Solution
> no idea
> 
> ## Steps to Reproduce
> 1. Connect a type-c wired headphone
> 2. play a file to produce sound through headphone
> 
> /device guacamoleb /version thirteen_plus

Can you get me some log?

**Comment by Ma-Asg** [comment]
Sorry I don't have root access and developer option in my phone.

**Comment by shantanu-sarkar** [comment]
> Sorry I don't have root access and developer option in my phone.

Flash this boot image and test again. Let me know if the issue exists.

https://drive.google.com/uc?export=download&id=1uhDXtT1WngOxmZrsaE5dgv54A6_D5AkS

_fastboot flash boot boot.img --slot=all_

**Comment by Ma-Asg** [comment]
It's done. I'll inform you about the result.
Thanks for swift response.

**Comment by Ma-Asg** [comment]
so far so good. It seems Okay.
Thanks @shantanu-sarkar.
