### ISSUE TITLE
Pixel Experience wont update over the air on veux

### ISSUE THREAD

**Issue by ThimothyXYZ123** [PixelExperience/android-issues#4208]
## Build date

PixelExperience_Plus_veux-13.0-20230112-0341-OFFICIAL

## Expected Behavior

Device should update normally 

## Current Behavior

Pixel Experience gets stuck on verifying update 

## Possible Solution

Edit here

## Steps to Reproduce

1.open settings 
2.check for update on device veux
3.doenload update
4.try to install the update

/device veux
/version thirteen_plus

**Comment by ThimothyXYZ123** [comment]
Workaround is to update via recovery , hence issue can be solved

**Comment by Rahul1d** [comment]
> Workaround is to update via recovery , hence issue can be solved

Cannot update via recovery for the new build released on Feb 28th. 
Getting error in /sideload/package.zip

**Comment by brunobcestari** [comment]
me too. I'm getting the same error trying to update via recovery. Either on sideload and directly from the Android storage
