### ISSUE TITLE
Rom can't mount external storage in format that the Rom using to format it by default (kernel problem i guess)

### ISSUE THREAD

**Issue by plakonn** [PixelExperience/android-issues#4252]
## Build date

PixelExperience_Plus_apollo-13.0-20230106-0555-OFFICIAL

## Expected Behavior

After external USB storage is connected phone should be able to access it or ask you to format it (i think default format is exFAT) and then after format be able to access it.

## Current Behavior

I think new (LOS) kernel used since last update is not able to mount exFAT storage... so basically, after ROM asks you to format. Then it will tell you that "something is wrong with external storage" and ask you to format it again (which obviously don't work, because it formatting it still the same way, that cannot be mounted i think).

I think formatting external storage via recovery/pc to FAT32 makes it work fine.

## Possible Solution

idk... switch kernel to aosp one (previous one) or make the current one work with the format rom uses, suboptimal solution would be to make the rom to format external storage to FAT32 (which can be mounted and works fine as far i know)

## Steps to Reproduce

1.connect external storage via usb (exFAT)
2.let the phone format it (after it will tell you its needed)
3.try access it... (again it will tell you somethin is wrong, and ask you to format it again)

/device apollo
/version thirteen_plus

**Comment by Hlcpereira** [comment]
exfat support is to be expected to the next update.

**Comment by Hlcpereira** [comment]
Closed as per release of the (hugely delayed) february update.
