### ISSUE TITLE
Proximity sensor is not working properly

### ISSUE THREAD

**Issue by cavusabri** [PixelExperience/android-issues#4333]
## Build date

PixelExperience_miatoll-13.0-20230108-0338-OFFICIAL.zip

## Expected Behavior

The screen should be off during a call. I have to wait couple of seconds to place the phone to my ear or the screen stays on during the call. Proximity sensor should be ready right after i answered a call. 

## Current Behavior

Screen stays awake during call.

## Possible Solution

Should wait 2 seconds after the call is answered.

## Steps to Reproduce

1. Answer the call.
2.Wait two seconds.
3.Then place the phone to your ear.

/device miatoll
/version thirteen

**Comment by Mustafa7822** [comment]
Properly working in my device miatoll .how this issue is happening with you only?

**Comment by cavusabri** [comment]
> Properly working in my device miatoll .how this issue is happening with you only?

Try to place your phone to your ear right after you press the call button (quickly) or cover the sensor with your hand please. Mine is broken if your device locks the screen immediately. I always have to wait a couple of second.

**Comment by Mustafa7822** [comment]
Ohh then this issue can be fixed with proximity sensor hardware.only is this is hardware issue.

**Comment by cavusabri** [comment]
> Ohh then this issue can be fixed with proximity sensor hardware.only is this is hardware issue.

It was working fine on miui. Btw i have already replaced the p.sensor so i give up.

**Comment by Mustafa7822** [comment]
> > Ohh then this issue can be fixed with proximity sensor hardware.only is this is hardware issue.
> 
> It was working fine on miui. Btw i have already replaced the p.sensor so i give up.

Hope this can be fixed in next update
