### ISSUE TITLE
Fingerprint scanner not working as expected.

### ISSUE THREAD

**Issue by VikiVignesh026** [PixelExperience/android-issues#45]
## Build date

```
RQ2A.210405.005
PixelExperience_Plus_hotdogb-11.0-20210430-0218-OFFICIAL
```

## Expected Behavior

```
After adding the fingerprint, if we unlock the phone with a valid one it should unlock the phone
```

## Current Behavior

```
While unlocking the device with fingerprint, getting error as not recognised
```

## Possible Solution

```
Edit here
```

## Steps to Reproduce

```
1. Setup the fingerprint in security settings
2. Lock the phone
3. Try unlocking using fingerprint
4. Will get an error as not recognised.
```

/device hotdogb
/version eleven

**Comment by Chandra-Chaganti** [comment]
Currently, it's fixed in unofficial builds, same will be applied to upcoming official builds

**Comment by VikiVignesh026** [comment]
So, I can expect an OTA update for this right?
Or I have to install a fresh copy once it's released?

**Comment by Chandra-Chaganti** [comment]
> So, I can expect an OTA update for this right?
> Or I have to install a fresh copy once it's released?

yes you will get OTA(but not now)
