### ISSUE TITLE
Select Option In Recent App Screen Is Not Working.

### ISSUE THREAD

**Issue by rajsharma91** [PixelExperience/android-issues#4711]
## Build date

PixelExperience_Plus_miatoll-13.0-20230301-1818-OFFICIAL

## Expected Behavior

You Can Tap On The Select Button & System Will Identify Selectable Text From The App Screen Shown In The Recents View. You Can Then Select Text From It.

## Current Behavior

When We Tap On the Select Button From the Recent App Screen, Then Text Selection Does Not Work. Earlier, This Option Was Working In The Final Update Of PixelExperience Android 12.
Installed From PixelExperience Android 12 Final Update With Clean Flash Via PixelExperience Recovery.

## Possible Solution

I Don't Know

## Steps to Reproduce

1. Go To Any App ( For Example: Browser or YouTube Description Etc.).
2. Open Recent App Screen Then Tap On Select Option.
3. Than Notice Text Selection Does Not Work.

![Screenshot_20230312-122900_YouTube](https://user-images.githubusercontent.com/41617157/224529550-e2c4e5d9-ef1c-40af-8663-2aeb2b5a560d.png)
![Screenshot_20230312-122908_Pixel Launcher](https://user-images.githubusercontent.com/41617157/224529547-ee913036-3add-4fef-a664-1a60a650fe4a.png)

/device miatoll  
/version thirteen_plus

**Comment by Mustafa7822** [comment]
Not happening with me
