### ISSUE TITLE
Bluetooth icon in the volume panel gets glitched with the arrow while expanding the panel

### ISSUE THREAD

**Issue by Fufs** [PixelExperience/android-issues#472]
## Build date

Ever since pe11+ came out

## Expected Behavior

Nice smooth transitions

## Current Behavior

Icon gets glitched

## Possible Solution

Make the alpha value transition from 0 to 1 while expanding

## Steps to Reproduce

1. Install PE+
2. Connect to a bt headset
3. Expand volume panel

Note: Second half is slowed down
![glitch](https://user-images.githubusercontent.com/42976807/129197984-dec12d0f-ca11-40d1-9c49-608570320765.gif)

/device davinci
/version eleven_plus

**Comment by Jorg3Lucas** [comment]
@baalajimaestro

**Comment by baalajimaestro** [comment]
Source related issue. Can't fix.

**Comment by Jorg3Lucas** [comment]
Unfortunately we can't reproduce it here, if the issue persists, please open an issue again
