### ISSUE TITLE
insufficient microphone level when calling 

### ISSUE THREAD

**Issue by BlackRapids** [PixelExperience/android-issues#4726]
## Build date

 PixelExperience_Plus_blueline-13.0-20230301-1251-OFFICIAL

## Expected Behavior

The people I call should hear me clearly and loudly enough.

## Current Behavior

The people I call ask me to repeat as they don’t hear me loudly enough.

## Possible Solution

Fix the latest versions of Pixel Experience 13 and Pixel Experience Plus 13. The previous version (20221114) works fine.

## Steps to Reproduce

1. Install PixelExperience_Plus_blueline-13.0-20230301-1251-OFFICIAL.zip or on the phone.
2. Make a call.
3. Ask the person if you can be heard easily.
4.

/device blueline
/version thirteen_plus

**Comment by ReallySnow** [comment]
According to the test, this problem did not occur

**Comment by BlackRapids** [comment]
> According to the test, this problem did not occur

I had to roll back to 20221114 so that the microphone level was the same as before
you improved the sound in March, but not much enough

**Comment by amaxs** [comment]
Sounds like same issue from https://github.com/PixelExperience/android-issues/issues/4209

**Comment by BlackRapids** [comment]
#4740

**Comment by BlackRapids** [comment]
when making calls on the speakerphone, the interlocutor hears himself.
