### ISSUE TITLE
Factory Reset not working

### ISSUE THREAD

**Issue by Arjunr3108** [PixelExperience/android-issues#4777]
## Build date

PixelExperience_Plus_lava-13.0-20221114-0523-OFFICIAL.zip

## Expected Behavior

User data should be erased

## Current Behavior

Does not work, gets stuck at the option

## Possible Solution

Error code fix at system Integration and Functioning 

## Steps to Reproduce

1. Factory Reset from Recovery works but not through settings menu
2. Go to settings, system, reset options, erase all data, confirmation
3. Click on it and see the result
4. It looks like the button is pressed but the function of it is not working

/device lava
/version thirteen_plus

**Comment by Arjunr3108** [comment]
I use Poco M2

**Comment by Arjunr3108** [comment]
Redmi 9 uses Helio G35
Redmi 9 prime and poco M2 uses Helio G80

**Comment by HerrPanda** [comment]
I have this same issue on a Redmi 9 with Pixel Experience. It seems like this issue was closed but I don't find the solution or conclusion. I am sorry, I don't know well how GitHub works.
