### ISSUE TITLE
A certain game cannot launch after latest PE update

### ISSUE THREAD

**Issue by JamesKenway123** [PixelExperience/android-issues#4816]
## Build date

PixelExperience_Plus_avicii-13.0-20230326-0609-OFFICIAL.zip

## Expected Behavior

The game should launch normally without issue

## Current Behavior

The game does not launch at all and now displays as an error code 60 which indicates i have rooted device which my device isn't rooted at all

## Possible Solution

I think the update does not pass the validation of the game therefore it said it is rooted

## Steps to Reproduce

1. Download and install the game Priconne JP version from QooApp
2. Launch the game after installation

/device avicii
/version thirteen_plus
![Screenshot_20230328-223223_Spark](https://user-images.githubusercontent.com/114425155/228272701-3f333d5f-5e61-473c-b322-a0f09f337209.png)
![Screenshot_20230328-223207_Pixel Launcher](https://user-images.githubusercontent.com/114425155/228272725-e5ee3ff3-1256-417d-b3e5-c2119f44f2c6.png)

**Comment by JamesKenway123** [comment]
The developer has contacted me that the underlying issue is that my device is not operating in an "appropriate environment" therefore the latest PE update might be causing the issue.

**Comment by KakatkarAkshay** [comment]
No logs and that app isn't available on play store so I don't care
