### ISSUE TITLE
VPN closes when Play Store opens

### ISSUE THREAD

**Issue by htinlinnzaw** [PixelExperience/android-issues#4915]
## Build date

PixelExperience_Plus_ginkgo-13.0-20230402-0751-OFFICIAL

## Expected Behavior

VPN and Play Stores should work seamlessly

## Current Behavior

VPN closes when Play Store opens

## Possible Solution

Edit here

## Steps to Reproduce

1. Download latest PE rom for Redmi Note 8 (2023 April 2 Date) from Computer
2. Reboot into Recovery
3. Apply from adb
4. adb sideload PixelExperience.zip with Computer
5. Reboot into System
6. Redmi Note 8 Mobile Data connection works
7. Open VPN connection (in this case, I use Raptor VPN)
8. Other apps works seamlessly (eg, Telegram, Messenger)
9. Open Play Store
10. Then VPN closes

/device ginkgo
/version thirteen_plus

**Comment by Jorg3Lucas** [comment]
Hello, I hope you are well, thanks for your feedback/report, we have ended support for Android 13. We hope you will be with us in the future to make the Android 14 experience as stable as possible.
