### ISSUE TITLE
Device overheating while charging

### ISSUE THREAD

**Issue by 1nt18is091** [PixelExperience/android-issues#50]
## Build date

```
PixelExperience_Plus_beryllium-11.0-20210420-1257-OFFICIAL
```

## Expected Behavior

```
Shouldn't heat excessively while charging the device while not being used
```

## Current Behavior

```
Devices heats up excessively while charging the phone even if the devices is not being used and is idle
```

## Possible Solution

```
Edit here
```

## Steps to Reproduce

```
1.Connect your phone to charger
2.should start heating up despite not being used
3.
4.
```

/device beryllium
/version eleven_plus

**Comment by MaheshKingdom** [comment]
Nah. The device is more than 2.5 yrs old battery so automatically it will heat more than normal when charging with fast charger.. though it can't be considered overheating as summer season is going on and temp reaching 40C is normal.. i have tested and the temperature remains around 40C at max also 42C..👍
