### ISSUE TITLE
Bose Quietcomfort II keeps reconnecting when in Whatsapp/Signal/Discord (video)calls

### ISSUE THREAD

**Issue by cynster** [PixelExperience/android-issues#5031]
### Build Date

PixelExperience_Plus_guacamole-13.0-20230419-1652-OFFICIAL

### Device

guacamole

### Version

thirteen_plus

### Describe the Bug

Unfortunately Bluetooth seems to break when calling using Whatsapp/Signal/Discord.
It results in receiving no sound and me disconnecting the headset and holding the phone next to my ear.

- It doesn't matter if it's just a voice call or a video call.
- Bluetooth works fine without problems before call, like watching Youtube or Listening to Spotify. I can also hear it through the Bluetooth device when getting called. Only when entering the call things start to break.
- It doesn't seem to matter whether you call of get called
- It doesn't seem to be app-specific since the problem occurs in multiple apps tested: Whatsapp/Signal/Discord
- It doesn't seem to matter whether the Bluetooth device is connected before the call or during the call.
- Had the problem using Bose Quietcomfort II
- Same problem on both the Sennheiser Momentum True Wireless and Bose Quietcomfort II.
- I have tried re-paring the Bluetooth devices.
- I have tried it on a Samsung S8 running an unofficial build of the PixelExperience rom and it doesn't seem to be a problem here ([XDA forum link](https://forum.xda-developers.com/t/pixel-experience-plus-andorid-q-for-s8-s8-n8-unofficial-exynos.4083369/)). 

### Steps to Reproduce

1. Connect a Bluetooth device (preferably a headset) to the phone.
2. Call someone while using Bluetooth audio in Whatsapp/Signal/Discord.
3. [optional test] make someone call you and answer using Whatsapp/Signal/Discord.

### Expected Behavior

When calling or answering a call I expect the Bluetooth device to stay connected and not randomly disconnect. 
To clearly hear the other on the call.

**Comment by classified** [comment]
I tried using Galaxy Buds 2 Pro & OnePlus Buds z2 and it works fine. are you using any kind of mods or have changed any settings in developer options?

**Comment by cynster** [comment]
Last update PixelExperience_Plus_guacamole-13.0-20230506-1911-OFFICIAL has fixed the issues for me! Thanks!
