### ISSUE TITLE
Activating the display by swiping from bottom of the lockscreen.

### ISSUE THREAD

**Issue by ilia3367** [PixelExperience/android-issues#5051]
### Build Date

PixelExperience_Plus_beckham-13.0-20230422-0605-OFFICIAL

### Device

beckham

### Version

thirteen_plus

### Describe the Bug

In the previous build (PixelExperience_Plus_beckham-13.0-20230221-1404) it was possible on a locked phone after activating the display by swiping from bottom of the lockscreen to top to go to the home screen. Now this does not work.

### Steps to Reproduce

Now you can unlock only by lowering the notification panel.

### Expected Behavior

Please fix this problem so that you can unlock the device again by swiping up from the bottom of the lockscreen.

**Comment by willianwrm** [comment]
Did try it here, some events does works but some doesn't.

If the screen is activated by power button then the swipe up does work.
But if the screen is activated by a notification or proximity sensor then the swipe up does nothing.

**Comment by ilia3367** [comment]
> But if the screen is activated by a notification or proximity sensor then the swipe up does nothing.

Yes. The bottom-up swipe doesn't work, but the top-down swipe does when the notification panel opens. If you minimize it, you get to the desktop.

**Comment by ilia3367** [comment]
And one more request to the developer - please remove this misunderstanding "Aperture camera".
This is the worst camera app in existence.

**Comment by ilia3367** [comment]
Thank you very much for another ROM update!
But the problems I pointed out are still there.

**Comment by jro1979oliver** [comment]
I'm investigating this behavior. That kind of issue it's a bit hard to track.
About aperture camera it's a choice, you still can use a gcam in place, maybe I can make MotCam2 installable trough Playstore but is an app designed for older android versions

**Comment by ilia3367** [comment]
> I'm investigating this behavior. That kind of issue it's a bit hard to track.
Thank you for listening to your fans!

**Comment by ilia3367** [comment]
> About aperture camera

Unfortunately, this is not a device for which there can be great demands on the camera. The Moto Camera is enough for it.
There was a thread on XDA at https://forum.xda-developers.com/t/mod-moto-camera-2-for-any-rom-8-1-10-20200815-moto-z-play.3982969/ where there was a newer version of MotCamera, but that thread and the links to the Camera app are dead...
