### ISSUE TITLE
The N.F.C. stops working when the device is powered off.

### ISSUE THREAD

**Issue by williamfeng99** [PixelExperience/android-issues#5061]
### Build Date

PixelExperience_raphael_13.0-20230422-0329-OFFICIAL

### Device

raphael

### Version

thirteen_plus

### Describe the Bug

The device's N.F.C. stops functioning after the device is powered off, where the setting of it becomes unavailable as well, only rebooting the device twice or so brings the N.F.C. back to work.
![photo_2023-04-25_19-49-39](https://user-images.githubusercontent.com/75527080/234374266-a0361566-7f29-4d61-87cc-fc10dd43c6ab.jpg)

### Steps to Reproduce

1. Power off the device as normal.
2. Boot the device.
3. Look in the N.F.C. setting, it either becomes missing and untoggleable or unavailable.
4. Reboot the device once again, the N.F.C. restores its functionality.

### Expected Behavior

The N.F.C. is togglable all of the time and remains on/off regardless of the device status.

### Possible Solution

A [full logcat](https://github.com/PixelExperience/android-issues/files/11325864/nfc_err.log) is attached to this bug report for debugging.

There are few parts in this logcat where these lines will show:

2837  2837 F DEBUG   : Build fingerprint: 'Xiaomi/raphael/raphael:13/TQ2A.230405.003.E1/0329:userdebug/release-keys'
2837  2837 F DEBUG   : Revision: '0'
2837  2837 F DEBUG   : ABI: 'arm64'
2837  2837 F DEBUG   : Timestamp: 2023-04-25 19:42:00.190436041+0100
2837  2837 F DEBUG   : Process uptime: 1s
2837  2837 F DEBUG   : Cmdline: /vendor/bin/hw/android.hardware.nfc@1.2-service
2837  2837 F DEBUG   : pid: 2828, tid: 2828, name: android.hardwar  >>> /vendor/bin/hw/android.hardware.nfc@1.2-service <<<
2837  2837 F DEBUG   : uid: 1027
2837  2837 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
2837  2837 F DEBUG   : Abort message: 'Could not register service for NFC HAL Iface (-2147483648).'
2837  2837 F DEBUG   :     x0  0000000000000000  x1  0000000000000b0c  x2  0000000000000006  x3  0000007fe87e2350
2837  2837 F DEBUG   :     x4  4d1f716e651f6462  x5  4d1f716e651f6462  x6  4d1f716e651f6462  x7  7f7f7f7f7f7f7f7f
2837  2837 F DEBUG   :     x8  00000000000000f0  x9  000000770f6c1a10  x10 0000000000000001  x11 000000770f7035b0
2837  2837 F DEBUG   :     x12 0000007fe87e2310  x13 000000000000003c  x14 0000007fe87e24e0  x15 000a3b6f59f164f7
2837  2837 F DEBUG   :     x16 000000770f771d50  x17 000000770f74d640  x18 0000007719214000  x19 0000000000000b0c
2837  2837 F DEBUG   :     x20 0000000000000b0c  x21 00000000ffffffff  x22 0000000000000001  x23 0000000000000000
2837  2837 F DEBUG   :     x24 0000000000000000  x25 0000000000000000  x26 0000000000000000  x27 0000000000000000
2837  2837 F DEBUG   :     x28 0000000000000000  x29 0000007fe87e23d0
2837  2837 F DEBUG   :     lr  000000770f6f3408  sp  0000007fe87e2330  pc  000000770f6f3434  pst 0000000000000000

**Comment by Jorg3Lucas** [comment]
fixed in last build
