### ISSUE TITLE
Experiencing weird delays in receiving sms

### ISSUE THREAD

**Issue by jaganrajcj** [PixelExperience/android-issues#5131]
### Build Date

PixelExperience_Plus_miatoll-13.0-20230402-1037-OFFICIAL

### Device

miatoll

### Version

thirteen_plus

### Describe the Bug

Lately, with the Android 13 update, I've been experiencing a weird delay in receiving SMS. Some messages even take a couple of hours to receive, while some arrive in a few minutes. This is especially an issue with OTPs. I tried some common solutions like turning off the adaptive battery feature, setting no restriction on battery use of the messaging app, using different messaging apps, etc., but nothing worked. Some other sources said it's the issue with persist partition, but that should result in the malfunctioning of other sensors too right? not sure about that.

### Steps to Reproduce

Just request for some sort of OTPs or something.

### Expected Behavior

OTPs usually take a few minutes to a few hours to receive.

**Comment by Jorg3Lucas** [comment]
Hello, I hope you are well, thanks for your feedback/report, we have ended support for Android 13. We hope you will be with us in the future to make the Android 14 experience as stable as possible.
