### ISSUE TITLE
POCO X3 NFC YouTube and PureTuber BUG

### ISSUE THREAD

**Issue by jcyezzi96** [PixelExperience/android-issues#5190]
### Build Date

PixelExperience_Plus_surya-13.0-20230502-2357-OFFICIAL.zip

### Device

surya

### Version

thirteen_plus

### Describe the Bug

YouTube or similar apps not working properly and freezing the device when you are scrolling in the app and when you want to rotate the phone.

### Steps to Reproduce

*Open Youtube
*Select any video
*Minimize the video in the app
*Try scrolling in the app
*Or rotate the phone

### Expected Behavior

Don't freeze anymore

**Comment by CHRISL7** [comment]
Are you using standard YouTube? working fine here

**Comment by RisenID** [comment]
Device no longer supported by us.
