### ISSUE TITLE
[Surya] SystemUl crashes
randomly even when in standby and then Soft Reboot

### ISSUE THREAD

**Issue by sergiorgb** [PixelExperience/android-issues#52]
## Build date

```
: PixelExperience_Plus_surya-11.0-20210419-1213-OFFICIAL
```

## Expected Behavior

```
It shouldn`t crash
```

## Current Behavior

```
Sometimes when the phone is standby or i start the phone SystemUI Simply crashes i saw one time my phone doing the restart animation but i didnt restart it.
It simply crashes sometimes i dont know why it does that
```

## Possible Solution

```
Dont have
```

## Steps to Reproduce

```
1.Completely random sometimes u start your phone and there u have it 

```

/device surya
/version eleven_plus
I dont have any SystemUI Mods so i can say is fault of that but it isnt 
It isnt android security feature it is SystemUI crash
Today i had one of those crashes

**Comment by nullbytepl** [comment]
Stop spamming issues. Unless you have some real proof that it crashes (no, "I think it does" does not count) don't create any more.
