### ISSUE TITLE
5g not working on my Mi 11x 

### ISSUE THREAD

**Issue by siddhaarth010** [PixelExperience/android-issues#5220]
### Build Date

January 19, 2023

### Device

alioth

### Version

thirteen_plus

### Describe the Bug

it is showing me that the option selected is 5g ( recommended) however I'm not able to use 5g

### Steps to Reproduce

Nil

### Expected Behavior

5g Working

**Comment by SKULLMAXX** [comment]
Just revert back to stock rom and then again flash custom rom it will fix it but after that don't change firmware

**Comment by RisenID** [comment]
Device no longer supported by us.
