### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by bibekdanuwar** [PixelExperience/android-issues#5248]
### Build Date

TQ2A.230405.003.E1 PixelExperience_Plus_veux-13.0-20230419-0622-OFFICIAL

### Device

veux

### Version

thirteen_plus

### Describe the Bug

After turning on dark mode , settings and wallpapers are grey instead of dark. When restarting phone, darkmode works properly like , every interface are dark . But when we lock and unlock phone. Dark mode seems to display grey interface again instead of fully pitch dark mode, it implies on settings app, chrome and system wide

### Steps to Reproduce

Turn on dark mode. It will show greyish background instead of dark. When restarting device , dark mode seems to work properly for a while but when phone is locked and unlocked again,

### Expected Behavior

Everything just seems as before, dark interface changes into greyish interface again

### Possible Solution

Fix dark mode to make it fully dark and bring dolby Atmos support to veux as it supports Dolby Atmos sound

**Comment by RisenID** [comment]
Device no longer supported by us
