### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by sayantan722133** [PixelExperience/android-issues#5252]
### Build Date

05-05-2023

### Device

munch

### Version

thirteen_plus

### Describe the Bug

there is no dolby support and a good camera apk support

### Steps to Reproduce

there is no dolby support

### Expected Behavior

there is no dolby support

### Possible Solution

Please add dolby support and leica camera

**Comment by Vincent4440** [comment]
bruh

**Comment by jro1979oliver** [comment]
This is not an issue
