### ISSUE TITLE
Battery and auto shutdown 

### ISSUE THREAD

**Issue by PrasunJha15** [PixelExperience/android-issues#5278]
### Build Date

PixelExperience_Plus_RM6785-13.0-20230430-0605-OFFICIAL

### Device

RM6785

### Version

thirteen_plus

### Describe the Bug

The battery life is significantly lower than the Realme UI

And sometimes the phone automatically shuts down when receiving a call.

### Steps to Reproduce

Use the phone normally
And observe the fast battery drainage
And while receive calls

### Expected Behavior

The battery will drain fast and the phone will shut down automatically when receiving calls.

### Possible Solution

Optimization

**Comment by PrasunJha15** [comment]
The charging speed is also a little bit slow 
And Hotstar Video quality is also poor

**Comment by RisenID** [comment]
Device no longer supported by us
