### ISSUE TITLE
VoWiFi / WiFi Calling not working

### ISSUE THREAD

**Issue by alexismdr** [PixelExperience/android-issues#5286]
### Build Date

PixelExperience_crosshatch-13.0-20230504-2353-OFFICIAL

### Device

crosshatch

### Version

thirteen

### Describe the Bug

When connected to a wifi network, VoLTE remains enabled and VoWiFi does not.

### Steps to Reproduce

1. Check whether your operator offers VoLTE/VoWiFi
2. Disable WiFi
3. Dial `*#*#4636#*#*` on the default phone app
4. Open the top-right menu
5. Open to IMS service status
6. Check if VoLTE is "available"
7. Without leaving these settings, enable wifi in quick settings
8. Go back to IMS service status and check what's happening 

### Expected Behavior

VoLTE should go "unavailable" and VoWiFi should be "available". As a result, VoWiFi should be up and running.

### Possible Solution

May be linked to the CarrierConfig overlay or this problem: https://github.com/PixelExperience/android-issues/issues/5175.

**Comment by apernouille** [comment]
### Update! (what I've tried so far)

> 1. I noticed that the apns configuration was completely out of date so I updated it via a magisk module. I patched the kernel to avoid the known freezes bug on crosshatch linked to f2fs when installing magisk.
> 2. I found in logcat that the wfcactivation application (previously included in GMS) was missing, so I added it to crosshatch vendor and device repos.
> 3. I updated the pb files linked to CarrierSettings. As this had no effect on carrier configuration in settings, I generated a vendor.xml file for CarrierConfigOverlay based on these files (with carriersettings-extractor).
> 4. The only error line mentioning "VoWiFi" in logcat was "VoWiFi Roaming: value can't be changed". I tried to modify org.codeaurora.ims to remove the check that generated this error, but it caused other problems and I don't think it's a good solution.

_Most of my commits are available on my github as a fork_

I've been trying to solve this problem for several days now, but my limited knowledge of aosp prevents me from going any further.
Based on my extensive research and logcat analysis, I think a new way would be to update the ims service (org.codeaurora.ims) because it's the only one to log errors in logcat containing "VoWiFi". I'll try to do this by extracting it from a recent crosshatch lineage build. After that, I'll have no other idea.

**I've now come to ask for your help, as I know that the developers who regularly work on PE will have more experience in solving the problem I'm experiencing.**

Many thanks in advance,
Alexis

**Comment by apernouille** [comment]
As lineage contains almost the same ims apk, this did not fix the problem.

Enabling/disabling VoWiFi in the settings therefore leads to the following errors in logcat:
`QImsService: ImsConfigImpl : VoWiFi Roaming: value can't be changed
ImsConfigImplBase: Set provision value of 26 to 1 failed with error code 1`

I've tried enabling/disabling VoWiFi roaming via the CarrierConfigOverlay vendor.xml for my carrier, but nothing works.

From now on, I don't know what to do. I suspect that the telephony package stops in the VoWiFi activation steps when it tries to edit an unchangeable parameter (which leads to an error from the ImsService).

I'll try to update this issue if I get anything new but I'm really hamstrung by my poor knowledge of aosp.
**I really need help from the PE developers who are vastly more experienced than I am. I'm sure that any PE developer who doesn't necessarily work on Google devices would be able to help me, as the error doesn't seem to be specific to Pixels.**

Many thanks in advance,
Alexis

**Comment by alexismdr** [comment]
Is this issue really solved? @ZIDAN44

**Comment by ZIDAN44** [comment]
> Is this issue really solved? @ZIDAN44

This device is no longer maintained

**Comment by alexismdr** [comment]
@ZIDAN44 I've just seen on the PE website that no maintainer was listed. Was there any announcement for this deprecation? Has @PixelBoot stopped for good and are there any plans for someone to take over development?

**Comment by alexismdr** [comment]
Fixed by https://github.com/PixelDust-Devices/android_device_google_crosshatch/commit/410566efb8fc2bc3f96fc48c9952252f4784f8c6
