### ISSUE TITLE
ARCore crash/black screen (munch)

### ISSUE THREAD

**Issue by ReaperOQ** [PixelExperience/android-issues#5417]
### Build Date

PixelExperience_Plus_munch-13.0-20230715-0909-OFFICIAL

### Device

munch

### Version

thirteen_plus

### Describe the Bug

Any app that uses Google Services for AR crashes or showing black screen

### Steps to Reproduce

1. Open ARCore Depth Lab
2. See the black screen

1. Open Google app and search for any animal (e.g. tiger)
2. Select View in 3D
3. Select Show in your spaces
4. See activity crashing

### Expected Behavior

ARCore Depth Lab should show the image from the camera and the point on the surface that the camera is pointing at

**Comment by Jorg3Lucas** [comment]
Hello, I hope you are well, thanks for your feedback/report, we have ended support for Android 13. We hope you will be with us in the future to make the Android 14 experience as stable as possible.
