### ISSUE TITLE
System update notification always pops up but does nothing

### ISSUE THREAD

**Issue by GalaxymaxiS** [PixelExperience/android-issues#5420]
### Build Date

PixelExperience_Plus_avicii-13.0-20230507-1933-OFFICIAL

### Device

avicii

### Version

thirteen_plus

### Describe the Bug

It gives me a continuous notification of the update or the notification mentions: "Unable to install the update" - "Tap for more information". If I touch the notification then nothing happens it just goes away

here is a screenshot of the error:

![update_error](https://github.com/PixelExperience/android-issues/assets/57435746/e0e13121-ba48-4a4b-9e7c-616cfa063129)

_P.S: The language it's Italian so the notification is the red one where saying "Impossibile installare l'aggiornamento di sistema"_

### Steps to Reproduce

there is no step to perform just wait and it comes out by itself

### Expected Behavior

I expect it to open the update settings and give me "no updates"

**Comment by KakatkarAkshay** [comment]
Fixed
