### ISSUE TITLE
Original Google Camera Missing

### ISSUE THREAD

**Issue by max60213** [PixelExperience/android-issues#5468]
### Build Date

TQ3A.230705.001.B4 PixelExperience_blueline-13.0-20230724-0805-OFFICIAL

### Device

blueline

### Version

thirteen

### Describe the Bug

The original Google camera is missing, when I double click the power button, instead of the original one, the third party camera app pop up.
I miss the official Gcam...

### Steps to Reproduce

Double click the power button.

### Expected Behavior

Launch the Google Camera app.

**Comment by Bl4ck-3y3** [comment]
But it works fine with me.
