### ISSUE TITLE
Pixel launcher crashes when using the in-built screenshot button after swipe-up

### ISSUE THREAD

**Issue by tommifrance** [PixelExperience/android-issues#5497]
### Build Date

PixelExperience_Plus_raphael-13.0-20230527-1820-OFFICIAL

### Device

raphael

### Version

thirteen_plus

### Describe the Bug

https://github.com/PixelExperience/android-issues/assets/141156804/610701a0-0144-476b-8da6-4439fb549b4b

This doesn't happen when i take a screenshot using the menu that appears when pressing the power button.

### Steps to Reproduce

Open an app, swipe up, take a screenshot using the button circled in red.
![2023-08-01 17 32 47](https://github.com/PixelExperience/android-issues/assets/141156804/88b1a655-348d-4a55-bbbf-8cc50b5bc603)

### Expected Behavior

It souldn't crash, it should take a screenshot instead.

### Possible Solution

I'll attach a logcat, hope it helps
[logcat.txt](https://github.com/PixelExperience/android-issues/files/12231387/logcat.txt)

**Comment by jhenrique09** [comment]
Please check if you are using any magisk module related to Pixel, it seems that you are using outdated version of pixel launcher
