### ISSUE TITLE
Unable to Boot to recovery after installing new update (August 17 2021)

### ISSUE THREAD

**Issue by kamalkoushik24** [PixelExperience/android-issues#553]
## Build date

PixelExperience_whyred-11.0-20210817-0148-OFFICIAL_3

## Expected Behavior

When i flash the new updated rom the it should not encrypt the drive and let me boot into recovery

## Current Behavior

After flashing the pixel experience rom and rebooting to recovery the recovery freezes at splash screen and does not change.
After using the computer to boot into the recovery again the latest twrp does not work only the version form 3.2.2-9_0 are working. Even though they are working the device internal storage is being encrypted but the password is unknown, which makes me to wipe and go into the same loop of doing things.

## Possible Solution

If there is a code for encryption please remove it.

## Steps to Reproduce

1.Download the latest ROM of pixel experience.
2.Now wipe everything (Clean Wipe).
3.Install the zip using the flashing process.
4.Now boot to system and setup everything.
5.Reboot to recovery

/device whyred
/version eleven

**Comment by Jorg3Lucas** [comment]
The maintainer is using FBE for encryption so you will need to format data whenever you do clean flash
