### ISSUE TITLE
WiFi not working on new update (August 17 2021)

### ISSUE THREAD

**Issue by igorsvetlana** [PixelExperience/android-issues#557]
## Build date

PixelExperience_Plus_avicii-11.0-20210826-1603-OFFICIAL
PixelExperience_avicii-11.0-20210826-1603-OFFICIAL

## Expected Behavior

WiFi should work?

## Current Behavior

No WiFi shows up at all when you're searching for them.
Also get System UI isn't responding.

08-27 14:47:15.951 880 880 E android.hardware.wifi@1.0-service: Failed to write driver state control param: Invalid argument
08-27 14:47:15.952 880 880 E android.hardware.wifi@1.0-service: Failed to load WiFi driver
08-27 14:47:15.952 880 880 E android.hardware.wifi@1.0-service: Failed to initialize firmware mode controller
08-27 14:47:15.952 880 880 E android.hardware.wifi@1.0-service: Wifi HAL start failed

## Possible Solution

4G works...

## Steps to Reproduce

1. Clean install 
2. Tried both standard edition and plus.
3. [logcat.txt](https://github.com/PixelExperience/android-issues/files/7067108/logcat.txt)
4.

/device avicii
/version eleven_plus

**Comment by KakatkarAkshay** [comment]
Send output of `adb shell getprop | findstr sku`

**Comment by igorsvetlana** [comment]
**adb shell getprop | findstr sku**
[ro.boot.product.hardware.sku]: [7]

**Comment by KakatkarAkshay** [comment]
Fixed on latest build.
