### ISSUE TITLE
The options at the bottom of the camera app settings are displayed abnormally and cannot be clicked.

### ISSUE THREAD

**Issue by WaterKirby** [PixelExperience/android-issues#5622]
### Build Date

TQ3A.230805.001 PixelExperience_Plus_kebab-13.0-20230819-1141-OFFICIAL

### Device

kebab

### Version

thirteen_plus

### Describe the Bug

The options at the bottom of the camera app settings are displayed abnormally and cannot be clicked.

### Steps to Reproduce

Open Camera app settings.

### Expected Behavior

Raise the option so it clicks normally.

### Possible Solution

Use Gesture navigation.

**Comment by WaterKirby** [comment]
![Screenshot_20230830-192954_Camera](https://github.com/PixelExperience/android-issues/assets/36535628/5ad5e88c-c3d8-476b-a9dd-174a41cec552)

**Comment by Jorg3Lucas** [comment]
Hello, I hope you are well, thanks for your feedback/report, we have ended support for Android 13. We hope you will be with us in the future to make the Android 14 experience as stable as possible.
