### ISSUE TITLE
SD card Doesn't work

### ISSUE THREAD

**Issue by Joninx** [PixelExperience/android-issues#5648]
### Build Date

PixelExperience_Plus_ginkgo-13.0-20230812-1834-OFFICIAL

### Device

ginkgo

### Version

thirteen_plus

### Describe the Bug

When formating as external bootloop, when formating as internal it don't work and give an error: attempt to invoke virtual method 'java.lang.string android.os.storage [...]

### Steps to Reproduce

Try to format sd card as external or internal

### Expected Behavior

SD card funtioning as normal,

**Comment by Jorg3Lucas** [comment]
Hello, I hope you are well, thanks for your feedback/report, we have ended support for Android 13. We hope you will be with us in the future to make the Android 14 experience as stable as possible.
