### ISSUE TITLE
BATTERY DRAIN FAST ON POCO X3 

### ISSUE THREAD

**Issue by dhaval-arch** [PixelExperience/android-issues#5658]
### Build Date

PixelExperience_Plus_surya-13.0-20230818-1023-OFFICIAL

### Device

surya

### Version

thirteen_plus

### Describe the Bug

1.AFTER INSTALL PHONE BATTERY DRAINED VERY FAST CAN YOU SOLVE THIS PROBLEM 
2. Land scap use any song after swip notification shade not working properly up and down this has been freez brightness bar.

### Steps to Reproduce

NA

### Expected Behavior

NA

**Comment by CHRISL7** [comment]
Send a log, screenshot of battery statics. Also, are you using any module or custom kernel?

**Comment by dhaval-arch** [comment]
I AM NOT USING ANY MODULE OR CUSTOM KERNEL, ONLY USE PIXAL EXPERIENCE ROM
IN BUILD KERNEL USE.

BUG SHORTCUT NOT SHOW MY DEVELOPER OPTION I CAN'T SEND BUG REPORT.

**Comment by CHRISL7** [comment]
Send log using ADB, and send screenshot of battery stats.

**Comment by dhaval-arch** [comment]
NOT SHOWING ADB SEND LOG USING ADB IN DEVLOPER OPTION.

YOU HAVE TO GUIDE I WILL SEND IT WERE TO SEND LOG FILE

**Comment by CHRISL7** [comment]
adb logcat > logcat.log

**Comment by CHRISL7** [comment]
Still waiting for your screenshot

**Comment by dhaval-arch** [comment]
Please send i will confusion.

**Comment by dhaval-arch** [comment]
I FIND NEW BUG IN POCO X3

1:- USB TETHERING NOT WORK IN LOCK SCREEN.

**Comment by CHRISL7** [comment]
WTF bro, you are having random issues that are not present for me other user. Make sure you're not doing shit on your end. Also please provide a proper log or I will close this issue.

**Comment by dhaval-arch** [comment]
Please how to create log file please guide us.

**Comment by dhaval-arch** [comment]
Finnally Recived Logcat for poco x3

**Comment by RisenID** [comment]
Device no longer supported by us.
