### ISSUE TITLE
problem with ambient sensor on AOD

### ISSUE THREAD

**Issue by pocoloco1440** [PixelExperience/android-issues#5671]
### Build Date

PixelExperience_mojito-13.0-20230816-1812-OFFICIA

### Device

mojito

### Version

thirteen

### Describe the Bug

when the AOD is exposed to bright light it gets bright but doesn't dim back down when the light source is removed 

### Steps to Reproduce

- Turn on the AOD 
- bring the phone under a bright light source 
- remove the light source

### Expected Behavior

The AOD should dim back down when the light source is removed

**Comment by ZIDAN44** [comment]
Mojito dont have AOD like that
