### ISSUE TITLE
NFC not working 

### ISSUE THREAD

**Issue by Kaushikkampli** [PixelExperience/android-issues#5686]
### Build Date

September 

### Device

munch

### Version

thirteen_plus

### Describe the Bug

Unable to card for tap to pay on Cred.
Says device incompatible since it doesn't pass the safety checks.

### Steps to Reproduce

Open Cred
More options
Tap to pay
Skip to setup

### Expected Behavior

Tap to pay worked previously on miui

### Possible Solution

No idea

**Comment by JayanthKandula** [comment]
U need to lock bootloader for that to work.

**Comment by Kaushikkampli** [comment]
But since I am on a custom rom , I can't do that right?
Have to go back to MIUI?

**Comment by Jorg3Lucas** [comment]
Hello, I hope you are well, thanks for your feedback/report, we have ended support for Android 13. We hope you will be with us in the future to make the Android 14 experience as stable as possible.
