### ISSUE TITLE
Noticable delay when a call comes in 

### ISSUE THREAD

**Issue by Mustafa7822** [PixelExperience/android-issues#5693]
### Build Date

PixelExperience_miatoll-13.0-20230826-1456-OFFICIAL

### Device

miatoll

### Version

thirteen_plus

### Describe the Bug

When an incoming call is received, the phone appropriately rings and vibrates to alert the user. However, there is a noticeable delay in the visibility and functionality of the "Receive" button on the screen. potentially causing missed calls or delayed responses. This issue affects the overall user experience during incoming calls, as users expect a seamless and immediate response option when their phone rings.

### Steps to Reproduce

1. Ensure your phone is in a functional state with no ongoing software updates or known system issues.
2. Make sure your phone's ringer and vibration settings are enabled.
3. Wait for an incoming call.
4. When the call comes in, observe the screen for the appearance of the "Receive" button.
5. Note the delay between the phone ringing and vibrating to signal an incoming call and the "Receive" button becoming visible and functional on the screen.

### Expected Behavior

The user should be able to tap the "Receive" button without any noticeable delay to answer the call immediately.

### Possible Solution

I don't know

**Comment by Jorg3Lucas** [comment]
Hello, I hope you are well, thanks for your feedback/report, we have ended support for Android 13. We hope you will be with us in the future to make the Android 14 experience as stable as possible.
