### ISSUE TITLE
What does it stay on 0%

### ISSUE THREAD

**Issue by Nixobe** [PixelExperience/android-issues#5756]
### Build Date

PixelExperience_Plus_spes-13.0-20230821-0047-OFFICIAL

### Device

spes

### Version

thirteen_plus

### Describe the Bug

It stays on 0% until it dies
![Screenshot_20231010-013506_YouTube](https://github.com/PixelExperience/android-issues/assets/68926902/ffa65170-78b5-4d2b-a128-4303389f7562)

### Steps to Reproduce

Make it so that the remaining percentage on the phone is <1%

### Expected Behavior

Die when below 1%

### Possible Solution

Make sure it dies when it's 0%

**Comment by RisenID** [comment]
Device no longer supported by us.
