### ISSUE TITLE
Inspect device on chrome not showing page (developer mode is on)

### ISSUE THREAD

**Issue by harima34** [PixelExperience/android-issues#5772]
### Build Date

PixelExperience_Plus_raphael-13.0-20230815-1933-OFFICIAL

### Device

raphael

### Version

thirteen_plus

### Describe the Bug

Hi there, I cannot see page on Inspect google section, i can see the device but there is no page to inspect. Developer mode is on as i can publish my app (debug mode) from visual studio to my android, un adb console, if i do adb devices i can see my phone, i am not sure if that i missing something ? or is just not possible with this rom ? (The same app on my 2nd device can show me the page on chrome inspect, so the problem isn't the app, because even a page opened on chrome mobile didn't displayed on my computer).

Any clues ? Thanks

### Steps to Reproduce

Fresh install of the rom PixelExperience_Plus_raphael-13.0-20230815-1933-OFFICIAL, then turn on developer mode, then open a page on chrome on the device (or a debug app) then connect the phone, open chrome inspect on computer.

### Expected Behavior

Be able to see page for inspect

**Comment by zoya-reddit** [comment]
Any updates on this? Experiencing the same issue

**Comment by zoya-ali** [comment]
Any updates on this? Experiencing the same issue
