### ISSUE TITLE
Oneplus 6 Android 13 plus

### ISSUE THREAD

**Issue by Nashdodti** [PixelExperience/android-issues#5775]
### Build Date

Pixel experience August

### Device

enchilada

### Version

thirteen_plus

### Describe the Bug

Whenever you are on WhatsApp video call and you try to share your screen whole phone crashes and Wi-Fi and mobile data gets turned off and restart

Another work I had is whenever you are trying to connect to a Wi-Fi and mobile data is on as well all the status bar icons disappear

Mobile crashes when you take lot of pics on google camera

### Steps to Reproduce

Screen share your on WhatsApp video

Turn on mobile data and Wi-Fi same time and try to connect to new network using Wi-Fi

Install Google camera mod and click pictures

### Expected Behavior

It should not crash the WhatsApp app

The Icons should not disappear

And even when I am clicking photos with Google for camera phone shouldn't restart

**Comment by Jorg3Lucas** [comment]
Hello, I hope you are well, thanks for your feedback/report, we have ended support for Android 13. We hope you will be with us in the future to make the Android 14 experience as stable as possible.
