### ISSUE TITLE
Google Photos crashing, screen flickering, Front flash not working

### ISSUE THREAD

**Issue by ritzz36** [PixelExperience/android-issues#58]
## Build date

```
Example: PixelExperience_plus_albus_motoz2 play
```

## Expected Behavior

```
Google photos should not gets closed.
Front flash should work
3rd party launcher should work without getting closed
```

## Current Behavior

```
Google photos getting closed each time i open the same.
Front flash is not working while taking selfie 
Screen is flickering while scrolling in app drawer
```

## Possible Solution

```
Unknown
```

## Steps to Reproduce

```
1. Background activities of default apps should be given access so that proper functioning does not gets affected
2.
3.
4.
```

/device albus
/version eleven_plus

**Comment by ritzz36** [comment]
![Screenshot_20210515-134120_WhatsApp](https://user-images.githubusercontent.com/84223074/118353399-a3e57800-b583-11eb-9061-e2018f6acc55.png)

**Comment by jeangraff30** [comment]
Good morning, good afternoon, good night, thank you very much for the report.

About google photos, have you tried to clear the data?

On the front flash it is working on the device, but not on the standard camera, I will correct it in this update or the next.

About the third-party launcher, if you are having a problem you need to contact the application developer, we support the pixel launcher that comes standard in rom, about the report of the problem in the pixel launcher, I am already aware and I am providing a correction for this problem

I didn't understand about the reproduction of the problem, what problem are you talking about the background?

**Comment by ritzz36** [comment]
Yes jean, i have tried "clear data" step but the same is still not corrected.

**Comment by jeangraff30** [comment]
Do you have a telegram for me to send a test?

**Comment by jeangraff30** [comment]
Good afternoon, all reported issues have been resolved and a new build with fixes will be available soon.
