### ISSUE TITLE
issues with LTE+ unstable connection

### ISSUE THREAD

**Issue by robiee99** [PixelExperience/android-issues#5848]
### Build Date

PixelExperience_Plus_avicii-13.0-20231003-1348-OFFICIAL.zip

### Device

avicii

### Version

thirteen_plus

### Describe the Bug

unstable lte+ connection which causes buffering and other network related issues, when switched to other rom like superior os with force lte ca option this problem got resolved except this everything worked like a charm for me 

### Steps to Reproduce

I have examined this issue after changing 2-3 roms (crdroid, superioros, etc) and comparing lte+ connection stability with PixelExperience_Plus_avicii-13.0-20231003-1348-OFFICIAL.zip

### Expected Behavior

with the inclusion of force lte ca option this problem gets resolved 

### Possible Solution

include FORCE LTE CA option in network

**Comment by KakatkarAkshay** [comment]
Check after android 14 release as android 13 is eol
