### ISSUE TITLE
Redmi Note 6 Pro - Outgoing call no ringing 

### ISSUE THREAD

**Issue by hackbird79** [PixelExperience/android-issues#5858]
### Build Date

PixelExperience_Plus_tulip-13.0-20230328-0628-OFFICIAL

### Device

tulip

### Version

thirteen_plus

### Describe the Bug

First of all, thx for this amazing rom on redmi note 6 pro. Till now, all works perfect.
Just one thing is not working so well.
When i do an outgoing call my phone dont want to ring. Its still quiet. After a few moments the caller is just on the end.

### Steps to Reproduce

When i do an outgoing call my phone dont want to ring. Its still quiet. After a few moments the caller is just on the end.

### Expected Behavior

When i do an outgoing call my phone dont want to ring. Its still quiet. After a few moments the caller is just on the end.

**Comment by RisenID** [comment]
Device unsupported by us.
