### ISSUE TITLE
Dialer ID bug

### ISSUE THREAD

**Issue by Volverine** [PixelExperience/android-issues#5868]
### Build Date

PixelExperience_Plus_raphael-13.0-20231206-1306-OFFICIAL

### Device

raphael

### Version

thirteen_plus

### Describe the Bug

Whenever someone calls me, even if it's on contacts, the dialer (Google Dialer) shows this
<phone number of caller><my phone number>
In the notification, calling screen it appears as
<phone number of caller>&<my phone number>
This makes it to not display the contact name.

### Steps to Reproduce

Whenever someone calls me, even if it's on contacts, the dialer (Google Dialer) shows this
<phone number of caller><my phone number>
In the notification, calling screen it appears as
<phone number of caller>&<my phone number>
This makes it to not display the contact name.

### Expected Behavior

It just should display the dialer name.

**Comment by Jorg3Lucas** [comment]
its google side
