### ISSUE TITLE
Phone not Eligible to make contactless payments on Google Wallet

### ISSUE THREAD

**Issue by impactmike1** [PixelExperience/android-issues#5869]
### Build Date

PixelExperience_hotdog-13.0-20231122-0537-OFFICIAL

### Device

hotdog

### Version

thirteen_plus

### Describe the Bug

Even after the update I can't make contactless payments on my Oneplus 7T Pro

### Steps to Reproduce

![Screenshot_20231208-200342_Google Play services](https://github.com/PixelExperience/android-issues/assets/153315879/889be2e4-97c6-4e51-9f93-58ca8f2571c0)

### Expected Behavior

I hope it's fixed soon

**Comment by jro1979oliver** [comment]
This is due the new api implemented on Google side with a check for MEETS_DEVICE_INTEGRITY. For now, the workaround is using root and the well known PIF module (search for it as we won't support). Nothing is planned till now for 13 branch, so closing this as won't fix for now
