### ISSUE TITLE
At a Glance weather widget disappears after 1 day

### ISSUE THREAD

**Issue by andris155** [PixelExperience/android-issues#59]
At a Glance weather widget disappears after 1 day.

<img width="540" alt="Screenshot_20210515-135920" src="https://user-images.githubusercontent.com/8324198/118359980-faec4c80-b585-11eb-96ca-88ccb0c105c9.png">

## Build date

```
PixelExperience_beryllium-11.0-20210420-1257-OFFICIAL
```

## Expected Behavior

```
At a Glance weather widget no disappears after 1 day.
```

## Current Behavior

```
At a Glance weather widget disappears after 1 day.
```

## Possible Solution

```
Update the At a Glance weather widget if I turn on WiFi or any network. Currently updated only when phone is restarted.
```

## Steps to Reproduce

```
1. Start phone with WiFi on.
2. At a Glance weather widget is appear and updated.
3. Turn off WiFi and wait 1 day.
4. At a Glance weather widget disappears and no appear when turn on WiFi.
```

/device beryllium
/version eleven

**Comment by jhenrique09** [comment]
Google app issue, that happens randomly
