### ISSUE TITLE
Increase gain Bluetooth microphone

### ISSUE THREAD

**Issue by f0rodriguez** [PixelExperience/android-issues#5903]
### Build Date

PixelExperience_Plus_miatoll-13.0-20231123-2215-OFFICIAL.zip

### Device

miatoll

### Version

thirteen_plus

### Describe the Bug

I tested several Bluetooth devices under different configurations (absolute volume, a2dp & avrcp) and none works well (The person who receive the call complain because he can't listen well even with volume at maximum). Please, increase/booster the microphone in Bluetooth devices /hands free.
Thanks 

### Steps to Reproduce

Connect a Bluetooth handsfree and try to adjust the microphone volume, there is no way. 

### Expected Behavior

You could setup the microphone (Bluetooth) gain

### Possible Solution

Increase the default parameter

**Comment by Jorg3Lucas** [comment]
Hello, I hope you are well, thanks for your feedback/report, we have ended support for Android 13. We hope you will be with us in the future to make the Android 14 experience as stable as possible.
