### ISSUE TITLE
Impossibile configurare questo smartphone per i pagamenti contactless

### ISSUE THREAD

**Issue by guidobuldrighini** [PixelExperience/android-issues#5919]
### Build Date

PixelExperience_Plus_taimen-13.0-20231128-2143-OFFICIAL

### Device

taimen

### Version

thirteen_plus

### Describe the Bug

When I try to add my debit card to Google Wallet, it shows an error "This phone can't be set up to tap to pay"

### Steps to Reproduce

Steps to Reproduce
1- Open Wallet app
2- Add payment card
3- Payment card
4- New credit or debit card
5- Type card details in every field
6- Error screen:
![photo_2024-01-16_10-05-01](https://github.com/PixelExperience/android-issues/assets/1243192/879796d1-9624-4877-8d69-057becbbabb3)

### Expected Behavior

Accept debit card. Do payments with Google Wallet.

**Comment by Mic87xp1** [comment]
Same issue with Poco X5 Pro 5G
PixelExperience_Plus_redwood-13.0-20231123-1518-OFFICIAL.zip

**Comment by marktheprof** [comment]
> Same issue with Poco X5 Pro 5G (REDWOOD) PixelExperience_Plus_redwood-13.0-20231123-1518-OFFICIAL.zip

Seems to be the same issue for many Xiaomi and Poco smartphones... Hope there will be a fix soon!

**Comment by jro1979oliver** [comment]
This is due the new api implemented on Google side with a check for MEETS_DEVICE_INTEGRITY. For now, the workaround is using root and the well known PIF module (search for it as we won't support). Nothing is planned till now for 13 branch, so closing this as won't fix for now
