### ISSUE TITLE
X00TD BUG

### ISSUE THREAD

**Issue by dkpraveen99** [PixelExperience/android-issues#5920]
### Build Date

PixelExperience_Plus_X00TD-13.0-20231126-1607-OFFICIAL

### Device

X00TD

### Version

thirteen_plus

### Describe the Bug

I noticed an issue that after installing Nov 2023 build PE on x00td

> display peak brightness is becoming less 
> over heating
> Most importantly I faced a bad idle battery drain
>Network is slow 

### Steps to Reproduce

By install this build and using for several minutes you will feel the overheating
If you are using phone inside the room can get poor network
Just rest the phone for 5 to 6 hrs idle battery drain updo 10%

### Expected Behavior

I compared STOCK firmware 0.87 build.This issue is not seen on the stock rom

I can't find the reason for idle battery drain so I decided to change the battery after that It's not fixed please fix idle battery drain and overheating problem 

### Possible Solution

I tried to fix :-
Idle drain 
> adb commands to force doze mode
adb shell dumpsys deviceidle force-idle
> adb commands to check all activities
adb shell dumpsys activity processes
> Using greenify app to hibernate all app

Only YouTube and network is active by checking activity process 

After that I can't solve the problem  I think problem on kernel side 
Please rid off this problem in the next build

**Comment by AnandSuresh02** [comment]
Are you sure these issues are only with the latest build? Or all the previous builds have these issues?

**Comment by dkpraveen99** [comment]
**I don't know** this NOV 2023 build is my first try of PIXEL EXPERIENCE and I never installed any build before 

Just shifted from stock rom .087 to PixelExperience_Plus_X00TD-13.0-20231126-1607-OFFICIAL

After installed PIXEL EXPERIENCE I noticed that
1. Over Heating
2. Idle battery drain
 
This occurred from starting first day to till now
I thinked it was first day restoring process are going internally so they need some time for rom to set
But It not that case.

Thanks for your efforts give your best.

**Comment by dkpraveen99** [comment]
And Display full brightness level is little bit lower compared with stock rom (it based on the side by side comparison on two phone of same model one with STOCK ROM and other with PIXEL EXPERIENCE)

And I also checked on adb it shows 255 value in full brightness but it's not much bright

**Comment by dkpraveen99** [comment]
> Are you sure these issues are only with the latest build? Or all the previous builds have these issues?

I'm very sure this problem are in this Nov Build 

and I am not sure with the previous build and I never installed any previous build before.

**Comment by AnandSuresh02** [comment]
For the brightness issue, check if extra dim is turned on. And you can't expect this build to perform like the stock 087 build because it's much recent and heavier as compared with the stock android 9 rom. So the device will feel more battery drain than stock rom.

**Comment by dkpraveen99** [comment]
Thanks for your support 🙏

**Comment by dkpraveen99** [comment]
Solution for idle battery drain
1. Open Google files -->Apps --> System apps--> open Android system intelligent and Google play service
2. Disable that two apps
3. Enable that two apps
4. Scroll down and find App details (installed  from playstore) click and open that for each two apps
5. Click on update

By disable and re enable and update this two apps will solve the idle battery drain problem.

**Comment by dkpraveen99** [comment]
Another minor bug

Charge the phone in switched off state display is not turned off it shows black screen instead of trun off the screen

**Comment by Jorg3Lucas** [comment]
Hello, I hope you are well, thanks for your feedback/report, we have ended support for Android 13. We hope you will be with us in the future to make the Android 14 experience as stable as possible.
