### ISSUE TITLE
No sound in call sometimes

### ISSUE THREAD

**Issue by pratikmn15** [PixelExperience/android-issues#5939]
### Build Date

PixelExperience_Plus_mojito-13.0-20231217-1954-OFFICIAL

### Device

mojito

### Version

thirteen_plus

### Describe the Bug

Can't hear the person on the other side, it didn't used to happen in stock miui and then I have to reboot the device everytime to fix it.

### Steps to Reproduce

Just a normal phone call.

### Expected Behavior

Supposed to hear the person on the other side.

**Comment by dominiksramko** [comment]
I am experiencing the same issue for the past few months. It happens at least once a day.

**Comment by dominiksramko** [comment]
How come it's not supported if there's no other stable release yet?

**Comment by pratikmn15** [comment]
When is the Android 14 build coming out then?
