### ISSUE TITLE
About Battery

### ISSUE THREAD

**Issue by alaafathy22** [PixelExperience/android-issues#5944]
### Build Date

PixelExperience_Plus_sweet-13.0-20231123-0516-OFFICIAL.zip

### Device

sweet

### Version

thirteen_plus

### Describe the Bug

There is a problem with charging the battery, which takes much longer than necessary, and there is also a problem with draining the battery, which drains much faster than necessary, even if the battery saving mode is activated.

### Steps to Reproduce

There is a problem with charging the battery, which takes much longer than necessary, and there is also a problem with draining the battery, which drains much faster than necessary, even if the battery saving mode is activated.

### Expected Behavior

There is a problem with charging the battery, which takes much longer than necessary, and there is also a problem with draining the battery, which drains much faster than necessary, even if the battery saving mode is activated.

**Comment by alaafathy22** [comment]
Problem with phone note 10 pro xiaomi

**Comment by alaafathy22** [comment]
close

**Comment by Azzam0A0** [comment]
Install the stock rom first and install PE after. For some odd reason I had battery drainage issues when I Hopped from a custom rom to another custom rom. Going back to stock and then installing PE fixed it for me.

**Comment by alaafathy22** [comment]
@Azzam0A0

**Comment by Azzam0A0** [comment]
@alaafathy22 
Alright. Just make sure you follow the install guide and use PE recovery, to avoid any weird things happening.

**Comment by Jorg3Lucas** [comment]
Hello, I hope you are well, thanks for your feedback/report, we have ended support for Android 13. We hope you will be with us in the future to make the Android 14 experience as stable as possible.
