### ISSUE TITLE
org.pixelexperience.faceunlock fail

### ISSUE THREAD

**Issue by AlMagnan** [PixelExperience/android-issues#5948]
### Build Date

TQ3A.230901.001.B1 PixelExperience_Plus_jasmine_sprout-13.0-20231128-0817-OFFICIAL

### Device

jasmine_sprout

### Version

thirteen_plus

### Describe the Bug

Face unlock se cierra inesperadamente cada 2 minutos constantemente

### Steps to Reproduce

Just login and the error start

### Expected Behavior

Face unlock just work

**Comment by Jorg3Lucas** [comment]
Hello, I hope you are well, thanks for your feedback/report, we have ended support for Android 13. We hope you will be with us in the future to make the Android 14 experience as stable as possible.
