### ISSUE TITLE
Poco M3 shuts down after charger has been plugged in

### ISSUE THREAD

**Issue by k163791** [PixelExperience/android-issues#5953]
### Build Date

PixelExperience_citrus-13.0-20240209-1128-OFFICIAL

### Device

citrus

### Version

thirteen

### Describe the Bug

on Poco M3, everytime I plug in the charger, sometime after I check and the phone has been shut down, even when the charge was more than 30% when I plugged it in, this happens everytime I try to charge my phone, the charging works, but the phone shuts down when charging for some reason.

### Steps to Reproduce

Just plug your phone in, it should shut down after 5-10 mins.

### Expected Behavior

Phone should not shut down when plugged in.The phone

**Comment by Jorg3Lucas** [comment]
Hello, I hope you are well, thanks for your feedback/report, we have ended support for Android 13. We hope you will be with us in the future to make the Android 14 experience as stable as possible.
