### ISSUE TITLE
caption button on volume panel cant be pressed when in landscape mode

### ISSUE THREAD

**Issue by RadTDM** [PixelExperience/android-issues#77]
## Build date

```
Example: PixelExperience_Plus_raphael-11.0-20210418-0409-OFFICIAL
```

## Expected Behavior

```
The button should be pressable in landscape mode as well
```

## Current Behavior

```
Everytime the button is pressed, it doesnt toggle captions on or off. The button also shows that nothing is changed when pressed (as if that button isnt there at all), instead it just dismisses/close the entire volume panel
```

## Possible Solution

```
im sorry i have no experience in programming
```

## Steps to Reproduce

```
1. turn your phone to landscape mode
2. press the volume button
3. press the caption button
```

/device raphael
/version eleven_plus

**Comment by Jorg3Lucas** [comment]
> ## Build date
> ```
> Example: PixelExperience_Plus_raphael-11.0-20210418-0409-OFFICIAL
> ```
> 
> ## Expected Behavior
> ```
> The button should be pressable in landscape mode as well
> ```
> 
> ## Current Behavior
> ```
> Everytime the button is pressed, it doesnt toggle captions on or off. The button also shows that nothing is changed when pressed (as if that button isnt there at all), instead it just dismisses/close the entire volume panel
> ```
> 
> ## Possible Solution
> ```
> im sorry i have no experience in programming
> ```
> 
> ## Steps to Reproduce
> ```
> 1. turn your phone to landscape mode
> 2. press the volume button
> 3. press the caption button
> ```
> 
> /device raphael
> /version eleven_plus

Hello, you need to expand the volume panel to use this function

**Comment by RadTDM** [comment]
my bad, sorry for taking your time

**Comment by jhenrique09** [comment]
Testing a possible fix: https://gerrit.pixelexperience.org/c/frameworks_base/+/11817

**Comment by jhenrique09** [comment]
Fixed
