### ISSUE TITLE
Front camera is not working

### ISSUE THREAD

**Issue by Rocky1m3** [PixelExperience/android-issues#805]
## Build date

Pixel Experience RQ3A.210905.001
PixelExperience_Plus_X01BD-11.0-20210911-1041-OFFICIAL

## Expected Behavior

Normal functioning of front camera for taking photos, using front camera as a face cam to unlock the device (security measures)

## Current Behavior

Front camera has stopped working completely.
The front camera in camera app provided by Pixel Experience team is not working.
I am not even able to use face unlock anymore in my device.
Front camera in other gcam ports are also not working.

## Possible Solution

Edit here

## Steps to Reproduce

1.open the front camera app provided by official Pixel Experience team, you will get the error message.
2.Try to setup face unlock
3.
4.

/device X01BD
/version eleven_plus

**Comment by Jorg3Lucas** [comment]
Hello, I hope you're ok, unfortunately we don't support android 11 anymore and that's why we are closing the old issues, if the problem persists on android 12, please open a new issue
