### ISSUE TITLE
fingerprint scanner logo moving around on lockscreen

### ISSUE THREAD

**Issue by RadTDM** [PixelExperience/android-issues#83]
## Build date

```
PixelExperience_Plus_raphael-11.0-20210520-2031-OFFICIAL
```

## Expected Behavior

```
fingerprint logo should have stayed above the finger print scanner
```

## Current Behavior

```
sometimes the fingerprint logo can be found at different spots and have to be pressed there first before able to use fingerprint scanner
```

## Possible Solution

```
sorry, no idea
```

## Steps to Reproduce

```
1. press power button to turn on screen
```

/device raphael
/version eleven_plus
![Screenshot_20210521-203141~3](https://user-images.githubusercontent.com/84483274/119138619-a7da3400-ba74-11eb-8ac4-a66fc9f97fea.png)

**Comment by Jorg3Lucas** [comment]
apparently has been fixed in the update that I will post today
