### ISSUE TITLE
The Google Recorder app doesn't record

### ISSUE THREAD

**Issue by souzaguii** [PixelExperience/android-issues#840]
## Build date

PixelExperience_Plus_lavender-11.0-20210915-1722-OFFICIAL

## Expected Behavior

The recorder to record everything correctly.

## Current Behavior

The google recorder doesn't record anything, even on all types of microphone and with all permissions allowed. It only works on older versions.

## Possible Solution

A new patch with fixes

## Steps to Reproduce

1.Open the Google Recorder app.
2.Click on record button.
3.And it doesnt record anything.

/device lavender
/version eleven_plus

[Log_2021-10-08_21-56-10.txt](https://github.com/PixelExperience/android-issues/files/7314772/Log_2021-10-08_21-56-10.txt)

**Comment by samygti** [comment]
Go to the settings of the recorder application then in the Microphone section, finally, change the "Automatically detect ..." option to "Always use the telephone's microphone".
