### ISSUE TITLE
Brief description of your problem

### ISSUE THREAD

**Issue by Simon00500** [PixelExperience/android-issues#867]
## Build date

PixelExperience_Plus_vayu-11.0-20211010-1908-OFFICIAL

## Expected Behavior

I should take a screenshot and continue using my phone

## Current Behavior

I take a screenshot and then sound bar goes all the way to mute, then disappears for about 2 seconds then reappears for about 0.5 seconds and repeat, it doesn't happen every time but I have to lock and unlock my phone for this to go away, display touch doesn't work when the sound bar is up

## Possible Solution

Maybe disable sound bar while power button is pressed, but idk tho I'm just user

## Steps to Reproduce

1. Press power button and sound down at the same time, this will take a screenshot
2. Repeat until you find a bug, it usually happens around 1/10 times but it crashes other apps in normal use
3. If you can't find it try to press volume button first or power button first or both at the same time, it'll show up
4.

/device vayu
/version eleven_plus

**Comment by AlissonGrizotti** [comment]
Logs? ...

**Comment by Jorg3Lucas** [comment]
Hello, I hope you're ok, unfortunately we don't support android 11 anymore and that's why we are closing the old issues, if the problem persists on android 12, please open a new issue

**Comment by Simon00500** [comment]
Oh, I forgot qbout this, it's not your problem, it's also on corvus os and
arrow os(haven't tried more) everything solved with evolution X android 12
