### ISSUE TITLE
"Anti-flicker" function has no any effect on display

### ISSUE THREAD

**Issue by altirtix** [PixelExperience/android-issues#870]
## Build date

PixelExperience_Plus_avicii-11.0-20211011-1108-OFFICIAL.zip

## Expected Behavior

"Anti-flicker" function should reduce display flickering (PWM)

## Current Behavior

Unfortunately, the "Anti flicker" function has no any effect on PWM
Tested with a DSLR camera at a low shutter speed of 1/4000

## Possible Solution

Probably a kernel bug

## Steps to Reproduce

https://www.youtube.com/watch?v=AUfVMUVUkZI

/device avicii
/version eleven_plus

**Comment by Kedharnathan** [comment]
I am to getting a lot of flickering of my screen while playing games or setting a live wallpaper and it is fateful that I fear my screen would go off. Please help me to solve those problems, I hate my screen flickering so much.

**Comment by KakatkarAkshay** [comment]
Anti flicker is working fine for me.

**Comment by altirtix** [comment]
@KakatkarAkshay Does it work on current build? 
Have you watched my pinned video and have you checked the work of this function? 
For example, color degradation or camera tests?
If everything really works correctly, are there any tips on how to fix this for me?
Thanks in advance for feedback.

**Comment by KakatkarAkshay** [comment]
> @KakatkarAkshay Does it work on current build? Have you watched my pinned video and have you checked the work of this function? For example, color degradation or camera tests? If everything really works correctly, are there any any suggestion why this might have happened or tips on how to fix this for me? Thanks in advance for feedback.

I tested with phone camera with default settings and it seems to be working

**Comment by Jorg3Lucas** [comment]
Hello, I hope you're ok, unfortunately we don't support android 11 anymore and that's why we are closing the old issues, if the problem persists on android 12, please open a new issue

**Comment by Kedharnathan** [comment]
My greetings to you, thank you for your approach, I want you to do me a
favour, can you please tell me when you would release android 12 for
Motorola one power please?

**Comment by altirtix** [comment]
> > @KakatkarAkshay Does it work on current build? Have you watched my pinned video and have you checked the work of this function? For example, color degradation or camera tests? If everything really works correctly, are there any any suggestion why this might have happened or tips on how to fix this for me? Thanks in advance for feedback.
> 
> I tested with phone camera with default settings and it seems to be working

Hello. Can I ask you to remove this issue? The fact is that it is indexed by the search engine when someone tries to find me by nickname. This spoils my privacy. Thanks in advance.
