### ISSUE TITLE
[Redmi Note 8 - ginkgo] Very inconsistent media volume control for speaker output

### ISSUE THREAD

**Issue by yn4v4s** [PixelExperience/android-issues#876]
## Build date

PixelExperience_Plus_ginkgo-11.0-20211011-1511-OFFICIAL

## Expected Behavior

The media volume control should be consistent across the volume slider.

## Current Behavior

The speaker volume turns too low when is set below 80%, and almost imperceptible when set below 50%
(You have to put your ear very close to the speaker to be able to hear anything).
This doesn't happen when you use wired headphones, in that case, the volume control is consistent
and also louder than the stock OS.

## Steps to Reproduce

1. Play any audio from any application (YouTube, Spotify, WhatsApp audios, Telegram audios, etc)
2. Set the volume to 100%
3. Press volume down key
4. Start lowering the volume down to about 50%

/device ginkgo
/version eleven_plus

**Comment by Jorg3Lucas** [comment]
Hello, I hope you're ok, unfortunately we don't support android 11 anymore and that's why we are closing the old issues, if the problem persists on android 12, please open a new issue
