### ISSUE TITLE
Huge issue in battery backup and heating issue in Lavender device 

### ISSUE THREAD

**Issue by manab52425** [PixelExperience/android-issues#90]
## Build date

```
PixelExperience_Plus_lavender-11.0-20210514-1141-OFFICIAL
```

## Expected Behavior

```
A good battery backup
```

## Current Behavior

```
Lots of batteries running out in less time
```

## Possible Solution

```
Improvement in battery backup


```

## Steps to Reproduce

```
1. By Upgrading kernel
2. Via software update
3.
4.
```

/device lavender
/version eleven_plus
[logcat.txt](https://github.com/PixelExperience/android-issues/files/6602025/logcat.txt)
![Screenshot_20210528-142521_Settings](https://user-images.githubusercontent.com/84611056/119998279-2e9b8d80-bfee-11eb-8a6d-c2b23ce76214.png)
![Screenshot_20210528-224037_Settings](https://user-images.githubusercontent.com/84611056/120057572-b7074600-c061-11eb-9069-0e48953cd1ca.png)

**Comment by faham1997** [comment]
How do you upgrade kernel?

**Comment by manab52425** [comment]
> How do you upgrade kernel?

Via software update or via custom recovery. It's depends on you.

**Comment by faham1997** [comment]
I never said you could upgrade kernel . Did i?

**Comment by manab52425** [comment]
> How do you upgrade kernel?

Please fix this issue on June update.
