### ISSUE TITLE
google play crashes when pressing "install" button 

### ISSUE THREAD

**Issue by zahi101** [PixelExperience/android-issues#916]
## Build date

PixelExperience_Plus_cepheus-11.0-20210913-0518-OFFICIAL

## Expected Behavior

installing apps without crashing

## Current Behavior

after pressing the install button, the app is stuck and crash after some seconds (not every time installing app)

## Possible Solution

Edit here

## Steps to Reproduce

1.open google play
2.write "Facebook" in search (for Facebook the bug occurs every time)
3.press the "install" button
4.wait a few seconds -> crash

[logcat.txt](https://github.com/PixelExperience/android-issues/files/7380700/logcat.txt)
/device cepheus
/version eleven_plus

**Comment by RAHUL1115** [comment]
Just download latest version of play store from apk pure and install it and then reboot your device

**Comment by Jorg3Lucas** [comment]
Hello, I hope you're ok, unfortunately we don't support android 11 anymore and that's why we are closing the old issues, if the problem persists on android 12, please open a new issue
