### ISSUE TITLE
low mic output/robotic/distorted voice while calling over google duo/whatsapp

### ISSUE THREAD

**Issue by zaidanmeer** [PixelExperience/android-issues#925]
## Build date

 PixelExperience_Plus_violet-11.0-20210917-0431-OFFICIAL
 September 17, 2021 04:31 UTC

## Expected Behavior

Normally the person on the other-end should get a clear voice, like it's while calling normally form native dialer app using mobile network,

## Current Behavior

while calling from WhatsApp, the person on other end complained that your voice is like robotic/echo/distorted., did reset the phone still problem occurring , then i used google duo for a voice call, still robotic voice, same for videocalls , robotic distorted mic output

## Steps to Reproduce

1. Open WhatsApp
2. Call any test number** either voice/video
3. You will get robotic audio/distorted voice
4. If you call from normally using mobile network , and even check by recording app, microphone works perfectly.

/device  violet
/version eleven_plus

**Comment by zaidanmeer** [comment]
hi bro, I shifted back to P.E yesterday, install the latest build with security patch of November, I'm sharing the video, i recorded of voice on recipient phone

https://user-images.githubusercontent.com/25261907/143388955-ec0835d1-51f9-472e-8a2f-f3e9792d189e.mp4

**Comment by Virusvilla** [comment]
Same issue in my phone with previous and latest build for redmi note 7 pro.

**Comment by Jorg3Lucas** [comment]
Hello, I hope you're ok, unfortunately we don't support android 11 anymore and that's why we are closing the old issues, if the problem persists on android 12, please open a new issue
