### ISSUE TITLE
Wallpaper crop Aspect ratio in Styles & Wallpapers is wrong.

### ISSUE THREAD

**Issue by Darksoul20057** [PixelExperience/android-issues#937]
## Build date

PixelExperience_Plus_scorpio-11.0-20211013-0030-OFFICIAL

## Expected Behavior

Styles & Wallpapers should crop the wallpaper in 16:9 ratio as the mi note 2 is 16:9 ratio.

## Current Behavior

If I change my wallpaper, the Styles & Wallpapers  crops the photo in 18:9 aspect ratio because pixel phone are 18:9 and also it is taller than the mi note 2

## Possible Solution

Add Support for 16:9 ratio

## Steps to Reproduce

1.Not sure
2.
3.
4.

/device scorpio
/version eleven_plus

**Comment by Jorg3Lucas** [comment]
Hello, I hope you're ok, unfortunately we don't support android 11 anymore and that's why we are closing the old issues, if the problem persists on android 12, please open a new issue
