### ISSUE TITLE
Front facing camera not working. Device: sakura

### ISSUE THREAD

**Issue by arpitphillips** [PixelExperience/android-issues#94]
[logcat.txt](https://github.com/PixelExperience/android-issues/files/6532488/logcat.txt)

## Build date

```
RQ2A.210505.003
PixelExperience_Plus_sakura-11.0-20210516-0654-OFFICIAL
```

## Expected Behavior

```
Flip camera button should switch live view to front facing camera feed.
```

## Current Behavior

```
- Current camera app does not have front facing camera button.
- Using open camera and pressing flip button restarts back camera feed.
- trying to register face recognition under security gives error.
- (logs appended to report)
```

## Possible Solution

```
Don't know enough about what goes behind the scenes to give gyan :)
```

## Steps to Reproduce

```
1. Settings > Security > Face Unlock > Setup > Next > "Something Went Wrong"
2. Install Open Camera > press flip button 
3. Open Camera > no way to switch to front camera
4.
```

/device sakura
/version eleven_plus

**Comment by ZIDAN44** [comment]
Its working on my device..

**Comment by arpitphillips** [comment]
@ZIDAN44 this is happening. 


https://user-images.githubusercontent.com/61677889/119379741-7adc8a00-bcdd-11eb-91f2-162388a63fa5.mp4

**Comment by arpitphillips** [comment]
Seems like trying to switch between the front and rear just makes it switch between the two rear cameras because the objects shift only a little in the view. 
Would you like the logcat.txt again?

**Comment by arpitphillips** [comment]
Even the B612 app says unable to use camera.

![Screenshot_20210525-084649_B612](https://user-images.githubusercontent.com/61677889/119434472-e3575580-bd35-11eb-9a36-40d40705a477.png)

/device sakura
/version eleven_plus
