### ISSUE TITLE
Voice match: this feature is not available in your language

### ISSUE THREAD

**Issue by georgethemarmot** [PixelExperience/android-issues#96]
## Build date

```
PixelExperience_tissot-11.0-20210517-1224-OFFICIAL.zip
```

## Expected Behavior

```
Voice match should be toggleable
```

## Current Behavior

```
Voice match says it's not available in your language, no matter which language it's set to. It can't be turned on
```

## Possible Solution

```
N/A
```

## Steps to Reproduce

```
1. Open Google Assistant
2. Go to voice match
3. It says it's not available in your language no
```

/device tissot
/version eleven

**Comment by Abhinavgupta371** [comment]
I'm not sure but either it is due to soundtrigger or it just not supported for your language

Anyways I'll check it during next update.

**Comment by georgethemarmot** [comment]
Hi @Abhinavgupta371 , 
I've actually created the bug as a replica this one that was created for lavender device:
https://github.com/PixelExperience/android-issues/issues/60
the last comment might refer to this commit:
https://github.com/PixelExperience-Devices/device_xiaomi_lavender/commit/36f1dc2285b6399b7805838c6141ecdcb3448c42
I hope this can help.
