### ISSUE TITLE
Sound automatically drops to 0% when media is played on a bluetooth device and no sound coming from speaker of the device.

### ISSUE THREAD

**Issue by TheCruzJ4v5** [PixelExperience/android-issues#97]
[logcat.txt](https://github.com/PixelExperience/android-issues/files/6570044/logcat.txt)

## Build date

```
PixelExperience_Plus_beryllium-11.0-20210519-0726-OFFICIAL.zip
```

## Expected Behavior

```
The sound shouldn't drop when played on the Bluetooth device and when disconnected the sound should come out of the speaker
```

## Current Behavior

```
Sound automatically drops to 0% when media is played on a bluetooth device and no sound coming from speaker of the device when the Bluetooth is disconnected.
```

## Possible Solution

```
It's a software bug for sure.
```

## Steps to Reproduce

```
1.https://photos.app.goo.gl/qYh4NDqGGGhY1bqy8
2. This bug was once fixed by rebooting the device but, it came back when the phone was rebooting another time.
3.
![Screenshot_20210530-150506_Pixel_Launcher](https://user-images.githubusercontent.com/84717017/120149026-be1b8900-c206-11eb-8779-858fcc7a748e.png)

4.
```

/device beryllium
/version eleven_plus

**Comment by lakgarg** [comment]
Does this happen 100% of the time? Asking because it I've tried using multiple different bluetooth devices but everytime they worked as intended. Maybe try using another bluetooth device.

**Comment by TheCruzJ4v5** [comment]
Yes it happens on multiple Bluetooth devices even now.
Even no sounds come from device also.

**Comment by lakgarg** [comment]
It doesn't seem to be an issue on the ROM side. Please check if you're using any audio mods as such.

**Comment by TheCruzJ4v5** [comment]
I don't use any mods and I'm unrooted.
And can you please tell me what this means, because I'm new to this stuff
 #https://photos.app.goo.gl/3UMQ9UPfK6d5rwUi6
P.S thanks a lot for responding 😊
